/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_fundacion.vistas;

/**
 *
 * @author USUARIO
 */
public class CambioContrasena extends javax.swing.JFrame {

    /**
     * Creates new form CambioContrasena
     */
    public CambioContrasena() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        Cusuario = new javax.swing.JTextField();
        ContraseñaNueva = new javax.swing.JLabel();
        CContraNueva = new javax.swing.JTextField();
        ConfContras = new javax.swing.JLabel();
        CConfirContra = new javax.swing.JTextField();
        EnvioSolici = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ImagFNH = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Usuario.setText("Usuario:");
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        Cusuario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(Cusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 310, 30));

        ContraseñaNueva.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ContraseñaNueva.setText("Contraseña nueva:");
        jPanel1.add(ContraseñaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        CContraNueva.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(CContraNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 310, 30));

        ConfContras.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ConfContras.setText("Confirmar contraseña:");
        jPanel1.add(ConfContras, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 220, -1));

        CConfirContra.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(CConfirContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 310, 30));

        EnvioSolici.setBackground(new java.awt.Color(204, 204, 204));
        EnvioSolici.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        EnvioSolici.setText("Enviar Solicitud");
        EnvioSolici.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EnvioSolici.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnvioSoliciMouseClicked(evt);
            }
        });
        jPanel1.add(EnvioSolici, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 160, 50));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("ATRAS");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 160, 40));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ImagFNH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo fundaciónNH_400x400.jpg"))); // NOI18N
        ImagFNH.setText("fnhIma");
        ImagFNH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(ImagFNH, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(ImagFNH)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 660, 700));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cambio contraseña2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 270, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void EnvioSoliciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnvioSoliciMouseClicked
       this.dispose();
      Loggin ingresar = new Loggin();
      ingresar.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_EnvioSoliciMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CConfirContra;
    private javax.swing.JTextField CContraNueva;
    private javax.swing.JLabel ConfContras;
    private javax.swing.JLabel ContraseñaNueva;
    private javax.swing.JTextField Cusuario;
    private javax.swing.JButton EnvioSolici;
    private javax.swing.JLabel ImagFNH;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
