/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_fundacion.vistas;

/**
 *
 * @author nicro
 */
public class CreacionPersonas extends javax.swing.JFrame {

    /**
     * Creates new form CreacionPersonas
     */
    public CreacionPersonas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_principal = new javax.swing.JPanel();
        txt_tipo_documento = new javax.swing.JLabel();
        txt_numero_documento = new javax.swing.JLabel();
        txt_lugar_expedicion = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JLabel();
        txt_foto = new javax.swing.JLabel();
        txt_estrato = new javax.swing.JLabel();
        txt_fecha_nacimiento = new javax.swing.JLabel();
        txt_eps = new javax.swing.JLabel();
        txt_sisben = new javax.swing.JLabel();
        txt_categoria_sisben = new javax.swing.JLabel();
        txt_domicilio = new javax.swing.JLabel();
        txt_barrio = new javax.swing.JLabel();
        txt_localidad = new javax.swing.JLabel();
        txt_edad = new javax.swing.JLabel();
        box_tipo_documento = new javax.swing.JComboBox<>();
        Campo_num_documento = new javax.swing.JTextField();
        Campo_foto = new javax.swing.JTextField();
        Campo_lugar_expe1 = new javax.swing.JTextField();
        Campo_edad = new javax.swing.JTextField();
        Campo_nombres1 = new javax.swing.JTextField();
        Date_fecha_naci = new com.toedter.calendar.JDateChooser();
        Campo_apellidos1 = new javax.swing.JTextField();
        Campo_barrio = new javax.swing.JTextField();
        Campo_localidad = new javax.swing.JTextField();
        Campo_domicilio = new javax.swing.JTextField();
        Campo_eps = new javax.swing.JTextField();
        Radio_sisben_no = new javax.swing.JRadioButton();
        Radio_sisben_si = new javax.swing.JRadioButton();
        Campo_estrato1 = new javax.swing.JTextField();
        Campo_categoria_sis1 = new javax.swing.JTextField();
        txt_titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("fondo");
        setName("JFondo"); // NOI18N

        Panel_principal.setBackground(new java.awt.Color(255, 255, 255));
        Panel_principal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_tipo_documento.setText("Tipo de Documento:");

        txt_numero_documento.setText("Número de Documento:");

        txt_lugar_expedicion.setText("Lugar de Expedición:");

        txt_apellidos.setText("Apellidos:");

        txt_nombres.setText("Nombres:");

        txt_foto.setText("Fotografía:");

        txt_estrato.setText("Estrato:");

        txt_fecha_nacimiento.setText("Fecha de Nacimiento:");

        txt_eps.setText("Eps:");

        txt_sisben.setText("Sisben:");

        txt_categoria_sisben.setText("Categoria Sisben:");

        txt_domicilio.setText("Domicilio:");

        txt_barrio.setText("Barrio:");

        txt_localidad.setText("Localidad:");

        txt_edad.setText("Edad:");

        box_tipo_documento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Registro Civil", "Tarjeta de Identidad", "Cedulda de Ciudadania", "Cedula de extranjeria", " " }));

        Radio_sisben_no.setText("No");

        Radio_sisben_si.setText("Si");

        txt_titulo.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        txt_titulo.setForeground(new java.awt.Color(102, 102, 102));
        txt_titulo.setText("FORMULARIO INSCRIPCIÓN DE PERSONAS");

        javax.swing.GroupLayout Panel_principalLayout = new javax.swing.GroupLayout(Panel_principal);
        Panel_principal.setLayout(Panel_principalLayout);
        Panel_principalLayout.setHorizontalGroup(
            Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_principalLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Campo_eps, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(Panel_principalLayout.createSequentialGroup()
                                    .addComponent(Radio_sisben_si, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(Radio_sisben_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(Date_fecha_naci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_sisben)
                                .addComponent(txt_nombres)
                                .addComponent(box_tipo_documento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_tipo_documento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_lugar_expedicion)
                                .addComponent(txt_fecha_nacimiento)
                                .addComponent(txt_localidad)
                                .addComponent(txt_domicilio)
                                .addComponent(txt_eps)
                                .addComponent(Campo_lugar_expe1)
                                .addComponent(Campo_nombres1)
                                .addComponent(Campo_localidad, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Campo_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63)
                        .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Campo_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Campo_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_categoria_sisben)
                            .addComponent(txt_numero_documento)
                            .addComponent(txt_foto)
                            .addComponent(Campo_num_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Campo_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_edad)
                            .addComponent(txt_barrio)
                            .addComponent(txt_estrato)
                            .addComponent(txt_apellidos)
                            .addComponent(Campo_apellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Campo_estrato1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Campo_categoria_sis1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_titulo))
                .addGap(77, 77, 77))
        );
        Panel_principalLayout.setVerticalGroup(
            Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_principalLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txt_titulo)
                .addGap(30, 30, 30)
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addComponent(txt_tipo_documento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box_tipo_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_lugar_expedicion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_lugar_expe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_nombres1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_fecha_nacimiento))
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_numero_documento)
                            .addGroup(Panel_principalLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(Campo_num_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addComponent(txt_foto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_apellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_apellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_edad)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Date_fecha_naci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Campo_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_localidad)
                            .addComponent(txt_barrio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Campo_localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Campo_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_domicilio)
                            .addComponent(txt_estrato))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Campo_estrato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_sisben)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Radio_sisben_si)
                            .addComponent(Radio_sisben_no))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_eps)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_eps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addComponent(txt_categoria_sisben)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Campo_categoria_sis1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreacionPersonas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Campo_apellidos1;
    private javax.swing.JTextField Campo_barrio;
    private javax.swing.JTextField Campo_categoria_sis1;
    private javax.swing.JTextField Campo_domicilio;
    private javax.swing.JTextField Campo_edad;
    private javax.swing.JTextField Campo_eps;
    private javax.swing.JTextField Campo_estrato1;
    private javax.swing.JTextField Campo_foto;
    private javax.swing.JTextField Campo_localidad;
    private javax.swing.JTextField Campo_lugar_expe1;
    private javax.swing.JTextField Campo_nombres1;
    private javax.swing.JTextField Campo_num_documento;
    private com.toedter.calendar.JDateChooser Date_fecha_naci;
    private javax.swing.JPanel Panel_principal;
    private javax.swing.JRadioButton Radio_sisben_no;
    private javax.swing.JRadioButton Radio_sisben_si;
    private javax.swing.JComboBox<String> box_tipo_documento;
    private javax.swing.JLabel txt_apellidos;
    private javax.swing.JLabel txt_barrio;
    private javax.swing.JLabel txt_categoria_sisben;
    private javax.swing.JLabel txt_domicilio;
    private javax.swing.JLabel txt_edad;
    private javax.swing.JLabel txt_eps;
    private javax.swing.JLabel txt_estrato;
    private javax.swing.JLabel txt_fecha_nacimiento;
    private javax.swing.JLabel txt_foto;
    private javax.swing.JLabel txt_localidad;
    private javax.swing.JLabel txt_lugar_expedicion;
    private javax.swing.JLabel txt_nombres;
    private javax.swing.JLabel txt_numero_documento;
    private javax.swing.JLabel txt_sisben;
    private javax.swing.JLabel txt_tipo_documento;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables
}
