/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_fundacion.vistas;

/**
 *
 * @author USUARIO
 */
public class inscripciones extends javax.swing.JFrame {

    /**
     * Creates new form inscripciones
     */
    public inscripciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        setVisible(true);
        setLocationRelativeTo(null);
        setTitle("INSCRIPCIONES");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        TitIns = new javax.swing.JLabel();
        NomInsc = new javax.swing.JLabel();
        CNomInsc = new javax.swing.JTextField();
        CApelIns = new javax.swing.JLabel();
        ApellIns = new javax.swing.JTextField();
        SexoIns = new javax.swing.JLabel();
        TipDoc = new javax.swing.JLabel();
        jComboBoxTipDoc = new javax.swing.JComboBox<>();
        NumDoc = new javax.swing.JLabel();
        CNumDoc = new javax.swing.JTextField();
        CLugExp = new javax.swing.JTextField();
        LugExp1 = new javax.swing.JLabel();
        FecNAc = new javax.swing.JLabel();
        jDateChooserFecNAc = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        EdadIns = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        FecIns = new javax.swing.JLabel();
        FaseIns = new javax.swing.JLabel();
        CFasIns = new javax.swing.JTextField();
        CCodAsig = new javax.swing.JLabel();
        CCodASig = new javax.swing.JTextField();
        DirIns = new javax.swing.JLabel();
        CDirIns = new javax.swing.JTextField();
        BarrioIns = new javax.swing.JLabel();
        CBarrioInsc = new javax.swing.JTextField();
        JorFunIns = new javax.swing.JLabel();
        CJorFunIns = new javax.swing.JTextField();
        LocIns = new javax.swing.JLabel();
        CLocIns = new javax.swing.JTextField();
        EstIns = new javax.swing.JLabel();
        CFotIns = new javax.swing.JLabel();
        CamFotIns = new javax.swing.JTextField();
        TipProgIns = new javax.swing.JLabel();
        CTipProgIns = new javax.swing.JComboBox<>();
        ComMadIns = new javax.swing.JLabel();
        CComMadIns = new javax.swing.JComboBox<>();
        ConvPadrIns = new javax.swing.JLabel();
        CconvPadrIns = new javax.swing.JComboBox<>();
        CConvOtrIns = new javax.swing.JLabel();
        CConOtrIns = new javax.swing.JComboBox<>();
        DocComIns = new javax.swing.JLabel();
        CDocComIns = new javax.swing.JTextField();
        DocautIns = new javax.swing.JLabel();
        CDocAutIns = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        DatosAcadèmicos1 = new javax.swing.JLabel();
        Estudia = new javax.swing.JLabel();
        CampoEstudio1 = new javax.swing.JComboBox<>();
        Grado = new javax.swing.JLabel();
        CampoGrado1 = new javax.swing.JTextField();
        Colegio = new javax.swing.JLabel();
        CampoColegio1 = new javax.swing.JTextField();
        Jornada = new javax.swing.JLabel();
        CampoJornada1 = new javax.swing.JComboBox<>();
        DatosMedicos1 = new javax.swing.JLabel();
        EPS1 = new javax.swing.JLabel();
        CampoEps1 = new javax.swing.JTextField();
        Sisben1 = new javax.swing.JLabel();
        Categoria1 = new javax.swing.JLabel();
        TipoSangre1 = new javax.swing.JLabel();
        Peso1 = new javax.swing.JLabel();
        CampoPeso1 = new javax.swing.JTextField();
        Estatura1 = new javax.swing.JLabel();
        CampoEstatura1 = new javax.swing.JTextField();
        TallaZapat1 = new javax.swing.JLabel();
        CampoTallaZapa1 = new javax.swing.JTextField();
        TallaRopa1 = new javax.swing.JLabel();
        CampoTallaRopa1 = new javax.swing.JTextField();
        Discapacidad1 = new javax.swing.JLabel();
        CampoDiscapa1 = new javax.swing.JComboBox<>();
        NombDisca1 = new javax.swing.JLabel();
        Campodisc1 = new java.awt.TextArea();
        AlergíaMedic = new javax.swing.JLabel();
        CampoAlergMed = new javax.swing.JComboBox<>();
        Campoalermed = new java.awt.TextArea();
        AlergAlimento = new javax.swing.JLabel();
        CalergAlimen = new javax.swing.JComboBox<>();
        Campomed = new java.awt.TextArea();
        TomaMedicam1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Campomed1 = new java.awt.TextArea();
        DatosMadre2 = new javax.swing.JLabel();
        CampoNomMadr2 = new javax.swing.JLabel();
        CampoNomMad2 = new javax.swing.JTextField();
        ApellidosMadre2 = new javax.swing.JLabel();
        CamApellidos = new javax.swing.JTextField();
        TipdocMad1 = new javax.swing.JLabel();
        NumDoc1 = new javax.swing.JLabel();
        CNumDocM1 = new javax.swing.JTextField();
        LugarExpDoc = new javax.swing.JLabel();
        CLugExp1 = new javax.swing.JTextField();
        CFechNacM2 = new javax.swing.JLabel();
        DateMadIns = new com.toedter.calendar.JDateChooser();
        CNacM2 = new javax.swing.JLabel();
        CamNacM2 = new javax.swing.JTextField();
        EdadM2 = new javax.swing.JLabel();
        CEdadM2 = new javax.swing.JTextField();
        LocM2 = new javax.swing.JLabel();
        ClocM2 = new javax.swing.JTextField();
        BarrioViveM = new javax.swing.JLabel();
        CBarrioM2 = new javax.swing.JTextField();
        NivelEducM = new javax.swing.JLabel();
        CNivelEduM2 = new javax.swing.JTextField();
        CelularM = new javax.swing.JLabel();
        CCelM2 = new javax.swing.JTextField();
        FijoM = new javax.swing.JLabel();
        CFijoM2 = new javax.swing.JTextField();
        OcupaM = new javax.swing.JLabel();
        COcupM2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Datospadre2 = new javax.swing.JLabel();
        CampoNomPadre1 = new javax.swing.JLabel();
        CampoNomPad1 = new javax.swing.JTextField();
        ApellidosPadre1 = new javax.swing.JLabel();
        CApellPad1 = new javax.swing.JTextField();
        TipdocPad1 = new javax.swing.JLabel();
        NumDocPadre1 = new javax.swing.JLabel();
        CNumDocP1 = new javax.swing.JTextField();
        LugExpDocP1 = new javax.swing.JLabel();
        CLugExpP1 = new javax.swing.JTextField();
        CFechNacP1 = new javax.swing.JLabel();
        jDatePadIns = new com.toedter.calendar.JDateChooser();
        CNacP1 = new javax.swing.JLabel();
        CamNacP1 = new javax.swing.JTextField();
        EdadP1 = new javax.swing.JLabel();
        CEdadP1 = new javax.swing.JTextField();
        LocP1 = new javax.swing.JLabel();
        ClocP1 = new javax.swing.JTextField();
        BarriPadrins = new javax.swing.JLabel();
        CBarrioP1 = new javax.swing.JTextField();
        NivEducP1 = new javax.swing.JLabel();
        CNivelEduP1 = new javax.swing.JTextField();
        NumCelP1 = new javax.swing.JLabel();
        CCelP1 = new javax.swing.JTextField();
        TelFijP1 = new javax.swing.JLabel();
        CFijoP1 = new javax.swing.JTextField();
        OcupP1 = new javax.swing.JLabel();
        COcupP1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        DatosAcudiente = new javax.swing.JLabel();
        CampoNomAcud = new javax.swing.JLabel();
        CampoNomAcu = new javax.swing.JTextField();
        ApellidosAcu = new javax.swing.JLabel();
        CApellAcu = new javax.swing.JTextField();
        TipdocAcu = new javax.swing.JLabel();
        NumDocAcu = new javax.swing.JLabel();
        LugExpDocACu = new javax.swing.JLabel();
        CNumDocAcu = new javax.swing.JTextField();
        CLugExpAcu = new javax.swing.JTextField();
        CFechNacAcu = new javax.swing.JLabel();
        CNacAcu = new javax.swing.JLabel();
        EdadAcu = new javax.swing.JLabel();
        jDateAcudIns = new com.toedter.calendar.JDateChooser();
        CamNacAcu = new javax.swing.JTextField();
        CEdadAcu = new javax.swing.JTextField();
        LocAcu = new javax.swing.JLabel();
        ClocAcu = new javax.swing.JTextField();
        BarrioAcu = new javax.swing.JLabel();
        CBarrioAcu = new javax.swing.JTextField();
        NivEducAcu = new javax.swing.JLabel();
        CNivelEduAcu = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        DatosBasicosFamilia = new javax.swing.JLabel();
        DatBasFam = new javax.swing.JLabel();
        CHerVive = new javax.swing.JComboBox<>();
        CNomFamil1 = new javax.swing.JLabel();
        CanNomFam = new javax.swing.JTextField();
        ApellFami = new javax.swing.JLabel();
        CApellFami = new javax.swing.JTextField();
        EstudFam1 = new javax.swing.JLabel();
        CEstuFami1 = new javax.swing.JComboBox<>();
        CNomFamil2 = new javax.swing.JLabel();
        ApellFami2 = new javax.swing.JLabel();
        CanNomFam2 = new javax.swing.JTextField();
        CApellFami2 = new javax.swing.JTextField();
        EstudFam2 = new javax.swing.JLabel();
        CEstuFami2 = new javax.swing.JComboBox<>();
        CNomFamil3 = new javax.swing.JLabel();
        CanNomFam3 = new javax.swing.JTextField();
        ApellFami3 = new javax.swing.JLabel();
        CApellFami3 = new javax.swing.JTextField();
        EstudFam3 = new javax.swing.JLabel();
        CEstuFami3 = new javax.swing.JComboBox<>();
        CNomFamil4 = new javax.swing.JLabel();
        CanNomFam4 = new javax.swing.JTextField();
        ApellFami4 = new javax.swing.JLabel();
        CApellFami4 = new javax.swing.JTextField();
        EstudFam4 = new javax.swing.JLabel();
        CEstuFami4 = new javax.swing.JComboBox<>();
        OtrosParien = new javax.swing.JLabel();
        CEstuFami5 = new javax.swing.JComboBox<>();
        CNomOtPar1 = new javax.swing.JLabel();
        CanNomOtPar1 = new javax.swing.JTextField();
        ApellOtrPar1 = new javax.swing.JLabel();
        COtrPar1 = new javax.swing.JTextField();
        ParenOtPar1 = new javax.swing.JLabel();
        CNomOtPar = new javax.swing.JLabel();
        CanNomOtPar = new javax.swing.JTextField();
        ApellOtrPar = new javax.swing.JLabel();
        COtrPar = new javax.swing.JTextField();
        ParenOtPar = new javax.swing.JLabel();
        CNomOtPar2 = new javax.swing.JLabel();
        CanNomOtPar2 = new javax.swing.JTextField();
        ApellOtrPar2 = new javax.swing.JLabel();
        COtrPar2 = new javax.swing.JTextField();
        ParenOtPar2 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        ViviYOtros = new javax.swing.JLabel();
        DirecCasa = new javax.swing.JLabel();
        CdirecCasa = new javax.swing.JTextField();
        BarrioDatBas = new javax.swing.JLabel();
        CamBarrio = new javax.swing.JTextField();
        ViLocal1 = new javax.swing.JLabel();
        CamLocal1 = new javax.swing.JTextField();
        TipVivienda = new javax.swing.JLabel();
        TipSisben = new javax.swing.JLabel();
        CamTipSisben = new javax.swing.JComboBox<>();
        CatSisben = new javax.swing.JLabel();
        SerAgua = new javax.swing.JLabel();
        CamSerAgua = new javax.swing.JComboBox<>();
        SerLuz = new javax.swing.JLabel();
        CamSerLuz = new javax.swing.JComboBox<>();
        SerGas = new javax.swing.JLabel();
        CamSerGas = new javax.swing.JComboBox<>();
        SerInternet = new javax.swing.JLabel();
        CamSerInternet = new javax.swing.JComboBox<>();
        jSeparator8 = new javax.swing.JSeparator();
        ViviYOtros1 = new javax.swing.JLabel();
        ComidaFav = new javax.swing.JLabel();
        CComFavor = new javax.swing.JScrollPane();
        CComiFavor = new javax.swing.JTextArea();
        ColorFav = new javax.swing.JLabel();
        CColorFavor = new javax.swing.JScrollPane();
        CColorFav = new javax.swing.JTextArea();
        ActividadFav = new javax.swing.JLabel();
        CActiFavor = new javax.swing.JScrollPane();
        CActiviFav = new javax.swing.JTextArea();
        PersonajeFav = new javax.swing.JLabel();
        CPersFavo = new javax.swing.JScrollPane();
        CPersonajeFav = new javax.swing.JTextArea();
        RegistrarEstudiante = new javax.swing.JButton();
        BotAtrasInsPerCoord = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BotAtrasInsPerAdm1 = new javax.swing.JButton();
        jDateChooserFecNAc1 = new com.toedter.calendar.JDateChooser();
        CConOtrIns1 = new javax.swing.JComboBox<>();
        CConOtrIns2 = new javax.swing.JComboBox<>();
        jComboBoxTipDoc1 = new javax.swing.JComboBox<>();
        jComboBoxTipDoc2 = new javax.swing.JComboBox<>();
        jComboBoxTipDoc3 = new javax.swing.JComboBox<>();
        CConOtrIns3 = new javax.swing.JComboBox<>();
        CConOtrIns4 = new javax.swing.JComboBox<>();
        CApellFami5 = new javax.swing.JTextField();
        CApellFami6 = new javax.swing.JTextField();
        CApellFami7 = new javax.swing.JTextField();
        CConOtrIns5 = new javax.swing.JComboBox<>();
        CApellFami8 = new javax.swing.JTextField();
        jComboBoxTipDoc4 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 700));
        setResizable(false);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1114, 750));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 3800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 3800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TitIns.setText("INSCRIPCIONES");
        jPanel1.add(TitIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        NomInsc.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NomInsc.setText("Nombres");
        jPanel1.add(NomInsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        jPanel1.add(CNomInsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 190, -1));

        CApelIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CApelIns.setText("Apellidos");
        jPanel1.add(CApelIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        ApellIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellInsActionPerformed(evt);
            }
        });
        jPanel1.add(ApellIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 200, -1));

        SexoIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        SexoIns.setText("Sexo");
        jPanel1.add(SexoIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        TipDoc.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TipDoc.setText("Tipo De Documento");
        jPanel1.add(TipDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 150, -1));

        jComboBoxTipDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Targeta de identidad", "Cedula de ciudadania", "Numero de identificacion tributario", "cedula de extranjeria" }));
        jPanel1.add(jComboBoxTipDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 1770, 180, -1));

        NumDoc.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NumDoc.setText("Numero De Documento");
        jPanel1.add(NumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 170, -1));
        jPanel1.add(CNumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, 180, -1));
        jPanel1.add(CLugExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, -1));

        LugExp1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        LugExp1.setText("Lugar De Expedición");
        jPanel1.add(LugExp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, -1));

        FecNAc.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        FecNAc.setText("Fecha De Nacimiento");
        jPanel1.add(FecNAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));
        jPanel1.add(jDateChooserFecNAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, 200, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel1.setText("Ciudad De nacimiento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 180, -1));

        EdadIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        EdadIns.setText("Edad");
        jPanel1.add(EdadIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 180, -1));

        FecIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        FecIns.setText("Fecha De Inscripción");
        jPanel1.add(FecIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 170, -1, -1));

        FaseIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        FaseIns.setText("Fase");
        jPanel1.add(FaseIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        jPanel1.add(CFasIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, -1));

        CCodAsig.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CCodAsig.setText("Código Asignado");
        jPanel1.add(CCodAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 140, -1));
        jPanel1.add(CCodASig, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 200, -1));

        DirIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        DirIns.setText("Dirección");
        jPanel1.add(DirIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 70, -1));
        jPanel1.add(CDirIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 180, -1));

        BarrioIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BarrioIns.setText("Barrio");
        jPanel1.add(BarrioIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, -1, -1));
        jPanel1.add(CBarrioInsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 180, -1));

        JorFunIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        JorFunIns.setText("Jornada Fundación");
        jPanel1.add(JorFunIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 220, -1, -1));
        jPanel1.add(CJorFunIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 180, -1));

        LocIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        LocIns.setText("Localidad");
        jPanel1.add(LocIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        jPanel1.add(CLocIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 190, -1));

        EstIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        EstIns.setText("Estrato");
        jPanel1.add(EstIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        CFotIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CFotIns.setText("Fotografía");
        jPanel1.add(CFotIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));
        jPanel1.add(CamFotIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 180, -1));

        TipProgIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TipProgIns.setText("Tipo De Programa");
        jPanel1.add(TipProgIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, -1, -1));

        CTipProgIns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(CTipProgIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 180, -1));

        ComMadIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ComMadIns.setText("Convive con la Madre");
        jPanel1.add(ComMadIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, -1, -1));

        CComMadIns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Si", "No" }));
        jPanel1.add(CComMadIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 180, -1));

        ConvPadrIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ConvPadrIns.setText("Convive con el Padre");
        jPanel1.add(ConvPadrIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        CconvPadrIns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Si ", "No" }));
        jPanel1.add(CconvPadrIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 190, -1));

        CConvOtrIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CConvOtrIns.setText("Convive con otro");
        jPanel1.add(CConvOtrIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        CConOtrIns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "0", "1", "2", "3", " " }));
        jPanel1.add(CConOtrIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 200, -1));

        DocComIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        DocComIns.setText("Documento Compromiso");
        jPanel1.add(DocComIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));
        jPanel1.add(CDocComIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 180, -1));

        DocautIns.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        DocautIns.setText("Documento Autorización");
        jPanel1.add(DocautIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, -1, -1));
        jPanel1.add(CDocAutIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 180, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 1040, -1));

        DatosAcadèmicos1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        DatosAcadèmicos1.setText("Datos Académicos");
        jPanel1.add(DatosAcadèmicos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 180, 30));

        Estudia.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Estudia.setText("Estudia:");
        jPanel1.add(Estudia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        CampoEstudio1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Una Opción", "Si ", "No" }));
        CampoEstudio1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                CampoEstudio1ComponentAdded(evt);
            }
        });
        CampoEstudio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEstudio1ActionPerformed(evt);
            }
        });
        jPanel1.add(CampoEstudio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 170, -1));

        Grado.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Grado.setText("Grado:");
        jPanel1.add(Grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, 20));

        CampoGrado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoGrado1ActionPerformed(evt);
            }
        });
        jPanel1.add(CampoGrado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 180, -1));

        Colegio.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Colegio.setText("Colegio:");
        jPanel1.add(Colegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 90, 20));
        jPanel1.add(CampoColegio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 220, -1));

        Jornada.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Jornada.setText("Jornada");
        jPanel1.add(Jornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 150, 20));

        CampoJornada1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Una Opción" }));
        CampoJornada1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                CampoJornada1ComponentAdded(evt);
            }
        });
        CampoJornada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoJornada1ActionPerformed(evt);
            }
        });
        jPanel1.add(CampoJornada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, 260, -1));

        DatosMedicos1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        DatosMedicos1.setText("Datos Médicos");
        jPanel1.add(DatosMedicos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 160, -1));

        EPS1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        EPS1.setText("EPS:");
        jPanel1.add(EPS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 50, -1));
        jPanel1.add(CampoEps1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 190, -1));

        Sisben1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Sisben1.setText("Sisben:");
        jPanel1.add(Sisben1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, -1, -1));

        Categoria1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Categoria1.setText("Categoria:");
        jPanel1.add(Categoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, -1, -1));

        TipoSangre1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TipoSangre1.setText("Tipo de Sangre:");
        jPanel1.add(TipoSangre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, -1, -1));

        Peso1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Peso1.setText("Peso:");
        jPanel1.add(Peso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 580, -1, -1));
        jPanel1.add(CampoPeso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 600, 180, -1));

        Estatura1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Estatura1.setText("Estatura:");
        jPanel1.add(Estatura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));
        jPanel1.add(CampoEstatura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 180, -1));

        TallaZapat1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TallaZapat1.setText("Talla zapatos:");
        jPanel1.add(TallaZapat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, -1, -1));
        jPanel1.add(CampoTallaZapa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 660, 210, -1));

        TallaRopa1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TallaRopa1.setText("Talla Ropa:");
        jPanel1.add(TallaRopa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, -1, -1));
        jPanel1.add(CampoTallaRopa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 660, 190, -1));

        Discapacidad1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Discapacidad1.setText("Discapacidad");
        jPanel1.add(Discapacidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, -1, 20));

        CampoDiscapa1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opciòn", "Si", "No" }));
        jPanel1.add(CampoDiscapa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 710, 280, 30));

        NombDisca1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NombDisca1.setText("Nombre la discapacidad");
        jPanel1.add(NombDisca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 770, -1, -1));

        Campodisc1.setName("Describa cual o cuales"); // NOI18N
        jPanel1.add(Campodisc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 790, 1010, 60));

        AlergíaMedic.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        AlergíaMedic.setText("Alergico a algún medicamento");
        jPanel1.add(AlergíaMedic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 860, -1, -1));

        CampoAlergMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opciòn", "Si", "No" }));
        CampoAlergMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoAlergMedActionPerformed(evt);
            }
        });
        jPanel1.add(CampoAlergMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 860, 300, 20));
        jPanel1.add(Campoalermed, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 890, 1010, 50));

        AlergAlimento.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        AlergAlimento.setText("Alergico a algún alimento");
        jPanel1.add(AlergAlimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 950, -1, -1));

        CalergAlimen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Si", "No" }));
        jPanel1.add(CalergAlimen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 950, 300, 20));
        jPanel1.add(Campomed, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 980, 1010, 60));

        TomaMedicam1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TomaMedicam1.setText("Toma  algún medicamento:");
        jPanel1.add(TomaMedicam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1050, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Si", "No" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1050, 300, 20));
        jPanel1.add(Campomed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1080, 1010, 60));

        DatosMadre2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        DatosMadre2.setText("Datos Madre");
        jPanel1.add(DatosMadre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1200, 130, -1));

        CampoNomMadr2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CampoNomMadr2.setText("Nombres:");
        jPanel1.add(CampoNomMadr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1250, 80, -1));
        jPanel1.add(CampoNomMad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1270, 230, -1));

        ApellidosMadre2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ApellidosMadre2.setText("Apellidos:");
        jPanel1.add(ApellidosMadre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 1250, 90, -1));
        jPanel1.add(CamApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 1270, 230, -1));

        TipdocMad1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TipdocMad1.setText("Tipo de documento:");
        jPanel1.add(TipdocMad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 1250, -1, -1));

        NumDoc1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NumDoc1.setText("Número Documento:");
        jPanel1.add(NumDoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 1250, -1, -1));
        jPanel1.add(CNumDocM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 1270, 170, -1));

        LugarExpDoc.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        LugarExpDoc.setText("Lugar de expedición");
        jPanel1.add(LugarExpDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 1250, -1, 20));
        jPanel1.add(CLugExp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 1270, 190, 20));

        CFechNacM2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CFechNacM2.setText("Fecha de nacimiento:");
        jPanel1.add(CFechNacM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1310, -1, -1));
        jPanel1.add(DateMadIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1330, 230, -1));

        CNacM2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CNacM2.setText("Ciudad Nacimiento:");
        jPanel1.add(CNacM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 1310, -1, -1));
        jPanel1.add(CamNacM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 1330, 230, -1));

        EdadM2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        EdadM2.setText("Edad:");
        jPanel1.add(EdadM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 1310, 60, -1));
        jPanel1.add(CEdadM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 1330, 150, -1));

        LocM2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        LocM2.setText("Localidad");
        jPanel1.add(LocM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 1310, -1, -1));
        jPanel1.add(ClocM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 1330, 170, -1));

        BarrioViveM.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BarrioViveM.setText("Barrio");
        jPanel1.add(BarrioViveM, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 1310, 50, -1));
        jPanel1.add(CBarrioM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 1330, 180, -1));

        NivelEducM.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NivelEducM.setText("Nivel Educativo");
        jPanel1.add(NivelEducM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1370, -1, -1));
        jPanel1.add(CNivelEduM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1390, 230, -1));

        CelularM.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CelularM.setText("Celular:");
        jPanel1.add(CelularM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 1370, -1, -1));
        jPanel1.add(CCelM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 1390, 230, -1));

        FijoM.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        FijoM.setText("Fijo:");
        jPanel1.add(FijoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 1370, -1, -1));
        jPanel1.add(CFijoM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 1390, 150, -1));

        OcupaM.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        OcupaM.setText("Ocupaciòn:");
        jPanel1.add(OcupaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 1370, -1, -1));
        jPanel1.add(COcupM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 1390, 170, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 513, 1040, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1177, 1050, -1));

        Datospadre2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        Datospadre2.setText("Datos Padre");
        jPanel1.add(Datospadre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 1470, 130, -1));

        CampoNomPadre1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CampoNomPadre1.setText("Nombres:");
        jPanel1.add(CampoNomPadre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1510, -1, -1));
        jPanel1.add(CampoNomPad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1530, 240, -1));

        ApellidosPadre1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ApellidosPadre1.setText("Apellidos:");
        jPanel1.add(ApellidosPadre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1510, -1, -1));

        CApellPad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CApellPad1ActionPerformed(evt);
            }
        });
        jPanel1.add(CApellPad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1530, 230, -1));

        TipdocPad1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TipdocPad1.setText("Tipo de documento:");
        jPanel1.add(TipdocPad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 1510, -1, -1));

        NumDocPadre1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NumDocPadre1.setText("Número Documento:");
        jPanel1.add(NumDocPadre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 1510, -1, -1));
        jPanel1.add(CNumDocP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 1530, 170, -1));

        LugExpDocP1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        LugExpDocP1.setText("Lugar de expedición");
        jPanel1.add(LugExpDocP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 1510, -1, -1));
        jPanel1.add(CLugExpP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 1530, 170, -1));

        CFechNacP1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CFechNacP1.setText("Fecha de nacimiento:");
        jPanel1.add(CFechNacP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1570, -1, -1));
        jPanel1.add(jDatePadIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1590, 240, -1));

        CNacP1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CNacP1.setText("Ciudad Nacimiento:");
        jPanel1.add(CNacP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1570, -1, -1));
        jPanel1.add(CamNacP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1590, 230, -1));

        EdadP1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        EdadP1.setText("Edad:");
        jPanel1.add(EdadP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 1570, 60, -1));
        jPanel1.add(CEdadP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 1590, 160, -1));

        LocP1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        LocP1.setText("Localidad");
        jPanel1.add(LocP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 1570, -1, -1));
        jPanel1.add(ClocP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 1590, 170, -1));

        BarriPadrins.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BarriPadrins.setText("Barrio");
        jPanel1.add(BarriPadrins, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 1570, -1, -1));
        jPanel1.add(CBarrioP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 1590, 170, -1));

        NivEducP1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NivEducP1.setText("Nivel Educativo");
        jPanel1.add(NivEducP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1630, -1, -1));
        jPanel1.add(CNivelEduP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1650, 240, -1));

        NumCelP1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NumCelP1.setText("Celular:");
        jPanel1.add(NumCelP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1630, -1, -1));
        jPanel1.add(CCelP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1650, 230, -1));

        TelFijP1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TelFijP1.setText("Fijo:");
        jPanel1.add(TelFijP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 1630, -1, -1));
        jPanel1.add(CFijoP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 1650, 150, -1));

        OcupP1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        OcupP1.setText("Ocupaciòn:");
        jPanel1.add(OcupP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 1630, -1, -1));
        jPanel1.add(COcupP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 1650, 170, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1446, 1050, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1700, 1060, -1));

        DatosAcudiente.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        DatosAcudiente.setText("Datos Acudiente");
        jPanel1.add(DatosAcudiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 1720, 160, -1));

        CampoNomAcud.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CampoNomAcud.setText("Nombres:");
        jPanel1.add(CampoNomAcud, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1750, -1, -1));
        jPanel1.add(CampoNomAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1770, 240, -1));

        ApellidosAcu.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ApellidosAcu.setText("Apellidos:");
        jPanel1.add(ApellidosAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1750, 80, -1));

        CApellAcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CApellAcuActionPerformed(evt);
            }
        });
        jPanel1.add(CApellAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1770, 230, -1));

        TipdocAcu.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TipdocAcu.setText("Tipo de documento:");
        jPanel1.add(TipdocAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 1750, -1, 20));

        NumDocAcu.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NumDocAcu.setText("Número Documento:");
        jPanel1.add(NumDocAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 1750, -1, 20));

        LugExpDocACu.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        LugExpDocACu.setText("Lugar de expedición");
        jPanel1.add(LugExpDocACu, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 1750, -1, 20));
        jPanel1.add(CNumDocAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 1770, 170, 20));
        jPanel1.add(CLugExpAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 1770, 160, 20));

        CFechNacAcu.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CFechNacAcu.setText("Fecha de nacimiento:");
        jPanel1.add(CFechNacAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1810, -1, -1));

        CNacAcu.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CNacAcu.setText("Ciudad Nacimiento:");
        jPanel1.add(CNacAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1810, -1, -1));

        EdadAcu.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        EdadAcu.setText("Edad:");
        jPanel1.add(EdadAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 1810, -1, -1));
        jPanel1.add(jDateAcudIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1830, 240, -1));
        jPanel1.add(CamNacAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1830, 230, -1));
        jPanel1.add(CEdadAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 1830, 160, -1));

        LocAcu.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        LocAcu.setText("Localidad");
        jPanel1.add(LocAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 1810, -1, -1));
        jPanel1.add(ClocAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 1830, 170, -1));

        BarrioAcu.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BarrioAcu.setText("Barrio");
        jPanel1.add(BarrioAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 1810, -1, -1));
        jPanel1.add(CBarrioAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 1830, 160, -1));

        NivEducAcu.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NivEducAcu.setText("Nivel Educativo");
        jPanel1.add(NivEducAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1870, 140, -1));
        jPanel1.add(CNivelEduAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1890, 240, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1933, 1050, -1));

        DatosBasicosFamilia.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        DatosBasicosFamilia.setText("Datos Basicos Familiares");
        jPanel1.add(DatosBasicosFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 1950, 230, -1));

        DatBasFam.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        DatBasFam.setText("Hermanos con los que convive:");
        jPanel1.add(DatBasFam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2010, -1, -1));

        CHerVive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "1", "2", "3", "4", "5", "6", "7", "8", "9", " " }));
        jPanel1.add(CHerVive, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 2010, 230, -1));

        CNomFamil1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CNomFamil1.setText("Nombres:");
        jPanel1.add(CNomFamil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2040, 140, -1));
        jPanel1.add(CanNomFam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2060, 340, -1));

        ApellFami.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ApellFami.setText("Apellidos:");
        jPanel1.add(ApellFami, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 2040, -1, -1));

        CApellFami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CApellFamiActionPerformed(evt);
            }
        });
        jPanel1.add(CApellFami, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 2060, 370, -1));

        EstudFam1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        EstudFam1.setText("Estudia:");
        jPanel1.add(EstudFam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 2040, -1, -1));

        CEstuFami1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Si", "No" }));
        jPanel1.add(CEstuFami1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 2060, 220, -1));

        CNomFamil2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CNomFamil2.setText("Nombres:");
        jPanel1.add(CNomFamil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2100, 80, -1));

        ApellFami2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ApellFami2.setText("Apellidos:");
        jPanel1.add(ApellFami2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 2100, 80, 20));
        jPanel1.add(CanNomFam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2120, 340, -1));

        CApellFami2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CApellFami2ActionPerformed(evt);
            }
        });
        jPanel1.add(CApellFami2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 2120, 370, 20));

        EstudFam2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        EstudFam2.setText("Estudia:");
        jPanel1.add(EstudFam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 2100, 120, -1));

        CEstuFami2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Si ", "No" }));
        jPanel1.add(CEstuFami2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 2120, 230, -1));

        CNomFamil3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CNomFamil3.setText("Nombres:");
        jPanel1.add(CNomFamil3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2170, -1, -1));
        jPanel1.add(CanNomFam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2190, 340, -1));

        ApellFami3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ApellFami3.setText("Apellidos:");
        jPanel1.add(ApellFami3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 2170, -1, -1));

        CApellFami3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CApellFami3ActionPerformed(evt);
            }
        });
        jPanel1.add(CApellFami3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 2190, 370, -1));

        EstudFam3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        EstudFam3.setText("Estudia:");
        jPanel1.add(EstudFam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 2170, 130, -1));

        CEstuFami3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Si ", "No" }));
        jPanel1.add(CEstuFami3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 2190, 230, -1));

        CNomFamil4.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CNomFamil4.setText("Nombres:");
        jPanel1.add(CNomFamil4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2240, -1, -1));
        jPanel1.add(CanNomFam4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2260, 340, -1));

        ApellFami4.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ApellFami4.setText("Apellidos:");
        jPanel1.add(ApellFami4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 2240, -1, -1));

        CApellFami4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CApellFami4ActionPerformed(evt);
            }
        });
        jPanel1.add(CApellFami4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 2680, 200, -1));

        EstudFam4.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        EstudFam4.setText("Estudia:");
        jPanel1.add(EstudFam4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 2240, -1, 20));

        CEstuFami4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Si", "No" }));
        jPanel1.add(CEstuFami4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 2260, 230, 20));

        OtrosParien.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        OtrosParien.setText("Otros parientes o personas con las que vive:");
        jPanel1.add(OtrosParien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2310, 320, -1));

        CEstuFami5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Si", "No" }));
        jPanel1.add(CEstuFami5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2330, 260, -1));

        CNomOtPar1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CNomOtPar1.setText("Nombres:");
        jPanel1.add(CNomOtPar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2370, -1, -1));
        jPanel1.add(CanNomOtPar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2390, 340, -1));

        ApellOtrPar1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ApellOtrPar1.setText("Apellidos:");
        jPanel1.add(ApellOtrPar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 2370, -1, -1));

        COtrPar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COtrPar1ActionPerformed(evt);
            }
        });
        jPanel1.add(COtrPar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 2390, 370, -1));

        ParenOtPar1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ParenOtPar1.setText("Parentesco:");
        jPanel1.add(ParenOtPar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 2370, -1, -1));

        CNomOtPar.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CNomOtPar.setText("Nombres:");
        jPanel1.add(CNomOtPar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2430, -1, -1));
        jPanel1.add(CanNomOtPar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2450, 340, -1));

        ApellOtrPar.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ApellOtrPar.setText("Apellidos:");
        jPanel1.add(ApellOtrPar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 2420, -1, 30));

        COtrPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COtrParActionPerformed(evt);
            }
        });
        jPanel1.add(COtrPar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 2450, 370, 20));

        ParenOtPar.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ParenOtPar.setText("Parentesco:");
        jPanel1.add(ParenOtPar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 2430, 140, -1));

        CNomOtPar2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CNomOtPar2.setText("Nombres:");
        jPanel1.add(CNomOtPar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2490, -1, -1));
        jPanel1.add(CanNomOtPar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2510, 340, -1));

        ApellOtrPar2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ApellOtrPar2.setText("Apellidos:");
        jPanel1.add(ApellOtrPar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 2490, 170, 20));

        COtrPar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COtrPar2ActionPerformed(evt);
            }
        });
        jPanel1.add(COtrPar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 2510, 370, 20));

        ParenOtPar2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ParenOtPar2.setText("Parentesco:");
        jPanel1.add(ParenOtPar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 2490, 150, -1));

        jSeparator7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2580, 1040, -1));

        ViviYOtros.setBackground(new java.awt.Color(240, 0, 240));
        ViviYOtros.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        ViviYOtros.setText("Datos Básicos Vivienda y Otros");
        jPanel1.add(ViviYOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 2610, -1, -1));

        DirecCasa.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        DirecCasa.setText("Dirección de la casa:");
        jPanel1.add(DirecCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2660, -1, -1));
        jPanel1.add(CdirecCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2680, 310, -1));

        BarrioDatBas.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BarrioDatBas.setText("Barrio:");
        jPanel1.add(BarrioDatBas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 2660, -1, -1));
        jPanel1.add(CamBarrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 2680, 210, -1));

        ViLocal1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ViLocal1.setText("Localidad:");
        jPanel1.add(ViLocal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 2660, -1, -1));

        CamLocal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamLocal1ActionPerformed(evt);
            }
        });
        jPanel1.add(CamLocal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 2680, 210, -1));

        TipVivienda.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TipVivienda.setText("Tipo de vivienda:");
        jPanel1.add(TipVivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 2660, 190, -1));

        TipSisben.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TipSisben.setText("Sisben:");
        jPanel1.add(TipSisben, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2720, -1, 20));

        CamTipSisben.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Si", "No" }));
        jPanel1.add(CamTipSisben, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2740, 310, 20));

        CatSisben.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CatSisben.setText("Categoria:");
        jPanel1.add(CatSisben, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 2720, -1, -1));

        SerAgua.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        SerAgua.setText("Servicio de Agua:");
        jPanel1.add(SerAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 2720, -1, -1));

        CamSerAgua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Si", "No" }));
        jPanel1.add(CamSerAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 2740, 210, -1));

        SerLuz.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        SerLuz.setText("Servicio de Luz:");
        jPanel1.add(SerLuz, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 2720, -1, -1));

        CamSerLuz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Si", "No" }));
        jPanel1.add(CamSerLuz, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 2740, 230, -1));

        SerGas.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        SerGas.setText("Servicio de Gas:");
        jPanel1.add(SerGas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2780, 140, -1));

        CamSerGas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Si", "No" }));
        jPanel1.add(CamSerGas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2800, 310, -1));

        SerInternet.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        SerInternet.setText("Servicio de Internet:");
        jPanel1.add(SerInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 2780, 150, -1));

        CamSerInternet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Si", "No" }));
        jPanel1.add(CamSerInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 2800, 210, -1));

        jSeparator8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2863, 1040, -1));

        ViviYOtros1.setBackground(new java.awt.Color(240, 0, 240));
        ViviYOtros1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        ViviYOtros1.setText("Intereses");
        jPanel1.add(ViviYOtros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 2880, -1, -1));

        ComidaFav.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ComidaFav.setText("Comida Favorita:");
        jPanel1.add(ComidaFav, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 2920, -1, -1));

        CComiFavor.setColumns(20);
        CComiFavor.setRows(5);
        CComiFavor.setText("Observaciones....");
        CComFavor.setViewportView(CComiFavor);

        jPanel1.add(CComFavor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 2940, 1030, -1));

        ColorFav.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ColorFav.setText("Color Favorito:");
        jPanel1.add(ColorFav, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 3040, -1, -1));

        CColorFav.setColumns(20);
        CColorFav.setRows(5);
        CColorFav.setText("Observaciones....");
        CColorFavor.setViewportView(CColorFav);

        jPanel1.add(CColorFavor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 3060, 1030, -1));

        ActividadFav.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ActividadFav.setText("Actividad Favorita:");
        jPanel1.add(ActividadFav, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 3150, -1, -1));

        CActiviFav.setColumns(20);
        CActiviFav.setRows(5);
        CActiviFav.setText("Observaciones....");
        CActiFavor.setViewportView(CActiviFav);

        jPanel1.add(CActiFavor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 3170, 1030, -1));

        PersonajeFav.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        PersonajeFav.setText("Personaje Favorito:");
        jPanel1.add(PersonajeFav, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 3260, -1, -1));

        CPersonajeFav.setColumns(20);
        CPersonajeFav.setRows(5);
        CPersonajeFav.setText("Observaciones....");
        CPersFavo.setViewportView(CPersonajeFav);

        jPanel1.add(CPersFavo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 3280, 1030, -1));

        RegistrarEstudiante.setBackground(new java.awt.Color(204, 204, 204));
        RegistrarEstudiante.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RegistrarEstudiante.setText("Registrar Estudiante");
        RegistrarEstudiante.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RegistrarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEstudianteActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 3380, 220, 40));

        BotAtrasInsPerCoord.setBackground(new java.awt.Color(204, 204, 204));
        BotAtrasInsPerCoord.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BotAtrasInsPerCoord.setText("IR A PERFIL COORD");
        BotAtrasInsPerCoord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotAtrasInsPerCoord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAtrasInsPerCoordActionPerformed(evt);
            }
        });
        jPanel1.add(BotAtrasInsPerCoord, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 3380, 160, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoFNH2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 110));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 680, 40));

        BotAtrasInsPerAdm1.setBackground(new java.awt.Color(204, 204, 204));
        BotAtrasInsPerAdm1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BotAtrasInsPerAdm1.setText("IR A PERFIL ADMIN");
        BotAtrasInsPerAdm1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotAtrasInsPerAdm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAtrasInsPerAdm1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotAtrasInsPerAdm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 3380, 160, 30));
        jPanel1.add(jDateChooserFecNAc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 200, -1));

        CConOtrIns1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jPanel1.add(CConOtrIns1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 600, 200, -1));

        CConOtrIns2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "A1", "A2", "A3", "A4", "A5", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11", "C12", "C13", "C14", "C15", "C16", "C17", "C18", "D1 _____D21" }));
        jPanel1.add(CConOtrIns2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 2740, 210, -1));

        jComboBoxTipDoc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Masculino", "Femenino" }));
        jPanel1.add(jComboBoxTipDoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 180, -1));

        jComboBoxTipDoc2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Tarjeta de identidad", "Cedula de ciudadania", "Numero de identificacion tributario", "cedula de extranjeria" }));
        jPanel1.add(jComboBoxTipDoc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 1270, 180, -1));

        jComboBoxTipDoc3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Tarjeta de identidad", "Cedula de ciudadania", "Numero de identificacion tributario", "cedula de extranjeria" }));
        jPanel1.add(jComboBoxTipDoc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 1530, 180, -1));

        CConOtrIns3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Si", "No" }));
        jPanel1.add(CConOtrIns3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 200, -1));

        CConOtrIns4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Si", "No" }));
        jPanel1.add(CConOtrIns4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, 200, 20));

        CApellFami5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CApellFami5ActionPerformed(evt);
            }
        });
        jPanel1.add(CApellFami5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 2260, 370, -1));

        CApellFami6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CApellFami6ActionPerformed(evt);
            }
        });
        jPanel1.add(CApellFami6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 2390, 200, -1));

        CApellFami7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CApellFami7ActionPerformed(evt);
            }
        });
        jPanel1.add(CApellFami7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 2450, 200, -1));

        CConOtrIns5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "A1", "A2", "A3", "A4", "A5", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11", "C12", "C13", "C14", "C15", "C16", "C17", "C18", "D1 _____D21" }));
        jPanel1.add(CConOtrIns5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 200, -1));

        CApellFami8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CApellFami8ActionPerformed(evt);
            }
        });
        jPanel1.add(CApellFami8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 2510, 200, -1));

        jComboBoxTipDoc4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Tarjeta de identidad", "Cedula de ciudadania", "Numero de identificacion tributario", "cedula de extranjeria", "Registro civil" }));
        jPanel1.add(jComboBoxTipDoc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 180, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoEstudio1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_CampoEstudio1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEstudio1ComponentAdded

    private void CampoEstudio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEstudio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEstudio1ActionPerformed

    private void CampoGrado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoGrado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoGrado1ActionPerformed

    private void CampoJornada1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_CampoJornada1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoJornada1ComponentAdded

    private void CampoJornada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoJornada1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoJornada1ActionPerformed

    private void CampoAlergMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoAlergMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoAlergMedActionPerformed

    private void CApellPad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CApellPad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CApellPad1ActionPerformed

    private void CApellAcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CApellAcuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CApellAcuActionPerformed

    private void CApellFamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CApellFamiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CApellFamiActionPerformed

    private void CApellFami2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CApellFami2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CApellFami2ActionPerformed

    private void CApellFami3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CApellFami3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CApellFami3ActionPerformed

    private void CApellFami4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CApellFami4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CApellFami4ActionPerformed

    private void COtrPar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COtrPar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COtrPar1ActionPerformed

    private void COtrParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COtrParActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COtrParActionPerformed

    private void COtrPar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COtrPar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COtrPar2ActionPerformed

    private void CamLocal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamLocal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CamLocal1ActionPerformed

    private void RegistrarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarEstudianteActionPerformed

    private void BotAtrasInsPerCoordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAtrasInsPerCoordActionPerformed
        this.dispose();
        PerfilCoordinador inscrip = new PerfilCoordinador();
        inscrip.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotAtrasInsPerCoordActionPerformed

    private void BotAtrasInsPerAdm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAtrasInsPerAdm1ActionPerformed
        this.dispose();
        PerfilAdministrador inscrip = new PerfilAdministrador();
        inscrip.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotAtrasInsPerAdm1ActionPerformed

    private void CApellFami5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CApellFami5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CApellFami5ActionPerformed

    private void CApellFami6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CApellFami6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CApellFami6ActionPerformed

    private void CApellFami7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CApellFami7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CApellFami7ActionPerformed

    private void CApellFami8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CApellFami8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CApellFami8ActionPerformed

    private void ApellInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellInsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellInsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActividadFav;
    private javax.swing.JLabel AlergAlimento;
    private javax.swing.JLabel AlergíaMedic;
    private javax.swing.JLabel ApellFami;
    private javax.swing.JLabel ApellFami2;
    private javax.swing.JLabel ApellFami3;
    private javax.swing.JLabel ApellFami4;
    private javax.swing.JTextField ApellIns;
    private javax.swing.JLabel ApellOtrPar;
    private javax.swing.JLabel ApellOtrPar1;
    private javax.swing.JLabel ApellOtrPar2;
    private javax.swing.JLabel ApellidosAcu;
    private javax.swing.JLabel ApellidosMadre2;
    private javax.swing.JLabel ApellidosPadre1;
    private javax.swing.JLabel BarriPadrins;
    private javax.swing.JLabel BarrioAcu;
    private javax.swing.JLabel BarrioDatBas;
    private javax.swing.JLabel BarrioIns;
    private javax.swing.JLabel BarrioViveM;
    private javax.swing.JButton BotAtrasInsPerAdm1;
    private javax.swing.JButton BotAtrasInsPerCoord;
    private javax.swing.JScrollPane CActiFavor;
    private javax.swing.JTextArea CActiviFav;
    private javax.swing.JLabel CApelIns;
    private javax.swing.JTextField CApellAcu;
    private javax.swing.JTextField CApellFami;
    private javax.swing.JTextField CApellFami2;
    private javax.swing.JTextField CApellFami3;
    private javax.swing.JTextField CApellFami4;
    private javax.swing.JTextField CApellFami5;
    private javax.swing.JTextField CApellFami6;
    private javax.swing.JTextField CApellFami7;
    private javax.swing.JTextField CApellFami8;
    private javax.swing.JTextField CApellPad1;
    private javax.swing.JTextField CBarrioAcu;
    private javax.swing.JTextField CBarrioInsc;
    private javax.swing.JTextField CBarrioM2;
    private javax.swing.JTextField CBarrioP1;
    private javax.swing.JTextField CCelM2;
    private javax.swing.JTextField CCelP1;
    private javax.swing.JTextField CCodASig;
    private javax.swing.JLabel CCodAsig;
    private javax.swing.JTextArea CColorFav;
    private javax.swing.JScrollPane CColorFavor;
    private javax.swing.JScrollPane CComFavor;
    private javax.swing.JComboBox<String> CComMadIns;
    private javax.swing.JTextArea CComiFavor;
    private javax.swing.JComboBox<String> CConOtrIns;
    private javax.swing.JComboBox<String> CConOtrIns1;
    private javax.swing.JComboBox<String> CConOtrIns2;
    private javax.swing.JComboBox<String> CConOtrIns3;
    private javax.swing.JComboBox<String> CConOtrIns4;
    private javax.swing.JComboBox<String> CConOtrIns5;
    private javax.swing.JLabel CConvOtrIns;
    private javax.swing.JTextField CDirIns;
    private javax.swing.JTextField CDocAutIns;
    private javax.swing.JTextField CDocComIns;
    private javax.swing.JTextField CEdadAcu;
    private javax.swing.JTextField CEdadM2;
    private javax.swing.JTextField CEdadP1;
    private javax.swing.JComboBox<String> CEstuFami1;
    private javax.swing.JComboBox<String> CEstuFami2;
    private javax.swing.JComboBox<String> CEstuFami3;
    private javax.swing.JComboBox<String> CEstuFami4;
    private javax.swing.JComboBox<String> CEstuFami5;
    private javax.swing.JTextField CFasIns;
    private javax.swing.JLabel CFechNacAcu;
    private javax.swing.JLabel CFechNacM2;
    private javax.swing.JLabel CFechNacP1;
    private javax.swing.JTextField CFijoM2;
    private javax.swing.JTextField CFijoP1;
    private javax.swing.JLabel CFotIns;
    private javax.swing.JComboBox<String> CHerVive;
    private javax.swing.JTextField CJorFunIns;
    private javax.swing.JTextField CLocIns;
    private javax.swing.JTextField CLugExp;
    private javax.swing.JTextField CLugExp1;
    private javax.swing.JTextField CLugExpAcu;
    private javax.swing.JTextField CLugExpP1;
    private javax.swing.JLabel CNacAcu;
    private javax.swing.JLabel CNacM2;
    private javax.swing.JLabel CNacP1;
    private javax.swing.JTextField CNivelEduAcu;
    private javax.swing.JTextField CNivelEduM2;
    private javax.swing.JTextField CNivelEduP1;
    private javax.swing.JLabel CNomFamil1;
    private javax.swing.JLabel CNomFamil2;
    private javax.swing.JLabel CNomFamil3;
    private javax.swing.JLabel CNomFamil4;
    private javax.swing.JTextField CNomInsc;
    private javax.swing.JLabel CNomOtPar;
    private javax.swing.JLabel CNomOtPar1;
    private javax.swing.JLabel CNomOtPar2;
    private javax.swing.JTextField CNumDoc;
    private javax.swing.JTextField CNumDocAcu;
    private javax.swing.JTextField CNumDocM1;
    private javax.swing.JTextField CNumDocP1;
    private javax.swing.JTextField COcupM2;
    private javax.swing.JTextField COcupP1;
    private javax.swing.JTextField COtrPar;
    private javax.swing.JTextField COtrPar1;
    private javax.swing.JTextField COtrPar2;
    private javax.swing.JScrollPane CPersFavo;
    private javax.swing.JTextArea CPersonajeFav;
    private javax.swing.JComboBox<String> CTipProgIns;
    private javax.swing.JComboBox<String> CalergAlimen;
    private javax.swing.JTextField CamApellidos;
    private javax.swing.JTextField CamBarrio;
    private javax.swing.JTextField CamFotIns;
    private javax.swing.JTextField CamLocal1;
    private javax.swing.JTextField CamNacAcu;
    private javax.swing.JTextField CamNacM2;
    private javax.swing.JTextField CamNacP1;
    private javax.swing.JComboBox<String> CamSerAgua;
    private javax.swing.JComboBox<String> CamSerGas;
    private javax.swing.JComboBox<String> CamSerInternet;
    private javax.swing.JComboBox<String> CamSerLuz;
    private javax.swing.JComboBox<String> CamTipSisben;
    private javax.swing.JComboBox<String> CampoAlergMed;
    private javax.swing.JTextField CampoColegio1;
    private javax.swing.JComboBox<String> CampoDiscapa1;
    private javax.swing.JTextField CampoEps1;
    private javax.swing.JTextField CampoEstatura1;
    private javax.swing.JComboBox<String> CampoEstudio1;
    private javax.swing.JTextField CampoGrado1;
    private javax.swing.JComboBox<String> CampoJornada1;
    private javax.swing.JTextField CampoNomAcu;
    private javax.swing.JLabel CampoNomAcud;
    private javax.swing.JTextField CampoNomMad2;
    private javax.swing.JLabel CampoNomMadr2;
    private javax.swing.JTextField CampoNomPad1;
    private javax.swing.JLabel CampoNomPadre1;
    private javax.swing.JTextField CampoPeso1;
    private javax.swing.JTextField CampoTallaRopa1;
    private javax.swing.JTextField CampoTallaZapa1;
    private java.awt.TextArea Campoalermed;
    private java.awt.TextArea Campodisc1;
    private java.awt.TextArea Campomed;
    private java.awt.TextArea Campomed1;
    private javax.swing.JTextField CanNomFam;
    private javax.swing.JTextField CanNomFam2;
    private javax.swing.JTextField CanNomFam3;
    private javax.swing.JTextField CanNomFam4;
    private javax.swing.JTextField CanNomOtPar;
    private javax.swing.JTextField CanNomOtPar1;
    private javax.swing.JTextField CanNomOtPar2;
    private javax.swing.JLabel CatSisben;
    private javax.swing.JLabel Categoria1;
    private javax.swing.JComboBox<String> CconvPadrIns;
    private javax.swing.JTextField CdirecCasa;
    private javax.swing.JLabel CelularM;
    private javax.swing.JTextField ClocAcu;
    private javax.swing.JTextField ClocM2;
    private javax.swing.JTextField ClocP1;
    private javax.swing.JLabel Colegio;
    private javax.swing.JLabel ColorFav;
    private javax.swing.JLabel ComMadIns;
    private javax.swing.JLabel ComidaFav;
    private javax.swing.JLabel ConvPadrIns;
    private javax.swing.JLabel DatBasFam;
    private com.toedter.calendar.JDateChooser DateMadIns;
    private javax.swing.JLabel DatosAcadèmicos1;
    private javax.swing.JLabel DatosAcudiente;
    private javax.swing.JLabel DatosBasicosFamilia;
    private javax.swing.JLabel DatosMadre2;
    private javax.swing.JLabel DatosMedicos1;
    private javax.swing.JLabel Datospadre2;
    private javax.swing.JLabel DirIns;
    private javax.swing.JLabel DirecCasa;
    private javax.swing.JLabel Discapacidad1;
    private javax.swing.JLabel DocComIns;
    private javax.swing.JLabel DocautIns;
    private javax.swing.JLabel EPS1;
    private javax.swing.JLabel EdadAcu;
    private javax.swing.JLabel EdadIns;
    private javax.swing.JLabel EdadM2;
    private javax.swing.JLabel EdadP1;
    private javax.swing.JLabel EstIns;
    private javax.swing.JLabel Estatura1;
    private javax.swing.JLabel EstudFam1;
    private javax.swing.JLabel EstudFam2;
    private javax.swing.JLabel EstudFam3;
    private javax.swing.JLabel EstudFam4;
    private javax.swing.JLabel Estudia;
    private javax.swing.JLabel FaseIns;
    private javax.swing.JLabel FecIns;
    private javax.swing.JLabel FecNAc;
    private javax.swing.JLabel FijoM;
    private javax.swing.JLabel Grado;
    private javax.swing.JLabel JorFunIns;
    private javax.swing.JLabel Jornada;
    private javax.swing.JLabel LocAcu;
    private javax.swing.JLabel LocIns;
    private javax.swing.JLabel LocM2;
    private javax.swing.JLabel LocP1;
    private javax.swing.JLabel LugExp1;
    private javax.swing.JLabel LugExpDocACu;
    private javax.swing.JLabel LugExpDocP1;
    private javax.swing.JLabel LugarExpDoc;
    private javax.swing.JLabel NivEducAcu;
    private javax.swing.JLabel NivEducP1;
    private javax.swing.JLabel NivelEducM;
    private javax.swing.JLabel NomInsc;
    private javax.swing.JLabel NombDisca1;
    private javax.swing.JLabel NumCelP1;
    private javax.swing.JLabel NumDoc;
    private javax.swing.JLabel NumDoc1;
    private javax.swing.JLabel NumDocAcu;
    private javax.swing.JLabel NumDocPadre1;
    private javax.swing.JLabel OcupP1;
    private javax.swing.JLabel OcupaM;
    private javax.swing.JLabel OtrosParien;
    private javax.swing.JLabel ParenOtPar;
    private javax.swing.JLabel ParenOtPar1;
    private javax.swing.JLabel ParenOtPar2;
    private javax.swing.JLabel PersonajeFav;
    private javax.swing.JLabel Peso1;
    private javax.swing.JButton RegistrarEstudiante;
    private javax.swing.JLabel SerAgua;
    private javax.swing.JLabel SerGas;
    private javax.swing.JLabel SerInternet;
    private javax.swing.JLabel SerLuz;
    private javax.swing.JLabel SexoIns;
    private javax.swing.JLabel Sisben1;
    private javax.swing.JLabel TallaRopa1;
    private javax.swing.JLabel TallaZapat1;
    private javax.swing.JLabel TelFijP1;
    private javax.swing.JLabel TipDoc;
    private javax.swing.JLabel TipProgIns;
    private javax.swing.JLabel TipSisben;
    private javax.swing.JLabel TipVivienda;
    private javax.swing.JLabel TipdocAcu;
    private javax.swing.JLabel TipdocMad1;
    private javax.swing.JLabel TipdocPad1;
    private javax.swing.JLabel TipoSangre1;
    private javax.swing.JLabel TitIns;
    private javax.swing.JLabel TomaMedicam1;
    private javax.swing.JLabel ViLocal1;
    private javax.swing.JLabel ViviYOtros;
    private javax.swing.JLabel ViviYOtros1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBoxTipDoc;
    private javax.swing.JComboBox<String> jComboBoxTipDoc1;
    private javax.swing.JComboBox<String> jComboBoxTipDoc2;
    private javax.swing.JComboBox<String> jComboBoxTipDoc3;
    private javax.swing.JComboBox<String> jComboBoxTipDoc4;
    private com.toedter.calendar.JDateChooser jDateAcudIns;
    private com.toedter.calendar.JDateChooser jDateChooserFecNAc;
    private com.toedter.calendar.JDateChooser jDateChooserFecNAc1;
    private com.toedter.calendar.JDateChooser jDatePadIns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
