
package Proyecto_fundacion.vistas;


public class Loggin extends javax.swing.JFrame {

   
    public Loggin() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setTitle("USUARIO Y CONTRASEÑA");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBordeImagen = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldUsusario = new javax.swing.JTextField();
        Usuario = new javax.swing.JLabel();
        Password_Usuario = new javax.swing.JPasswordField();
        Contraseña = new javax.swing.JLabel();
        jButtonIngresar = new javax.swing.JButton();
        jButtonOlvidoContraseña = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Mostar_Contraseña = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBordeImagen.setBackground(new java.awt.Color(204, 204, 255));
        jPanelBordeImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanelBordeImagen.setPreferredSize(new java.awt.Dimension(620, 700));

        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo fundaciónNH_400x400.jpg"))); // NOI18N
        jLabelImagen.setText("jLabel1");
        jLabelImagen.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanelBordeImagenLayout = new javax.swing.GroupLayout(jPanelBordeImagen);
        jPanelBordeImagen.setLayout(jPanelBordeImagenLayout);
        jPanelBordeImagenLayout.setHorizontalGroup(
            jPanelBordeImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBordeImagenLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        jPanelBordeImagenLayout.setVerticalGroup(
            jPanelBordeImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBordeImagenLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabelImagen)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelBordeImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 620, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(420, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldUsusario.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jTextFieldUsusario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jTextFieldUsusario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 360, 40));

        Usuario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Usuario.setText("USUARIO:");
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 210, 40));

        Password_Usuario.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        Password_Usuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(Password_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 360, 40));

        Contraseña.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Contraseña.setText("CONTRASEÑA:");
        jPanel1.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 180, 40));

        jButtonIngresar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonIngresar.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jButtonIngresar.setText("INGRESAR");
        jButtonIngresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIngresarMouseClicked(evt);
            }
        });
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 150, 30));

        jButtonOlvidoContraseña.setBackground(new java.awt.Color(204, 204, 204));
        jButtonOlvidoContraseña.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jButtonOlvidoContraseña.setText("Olvido su Contraseña?");
        jButtonOlvidoContraseña.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonOlvidoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOlvidoContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOlvidoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/USUARIO.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 230, 230));

        Mostar_Contraseña.setText("Mostrar Contraseña");
        Mostar_Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostar_ContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(Mostar_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIngresarMouseClicked
      this.dispose();
      PerfilAdministrador ingresar = new PerfilAdministrador();
      ingresar.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIngresarMouseClicked

    private void jButtonOlvidoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOlvidoContraseñaActionPerformed
        this.dispose();
      CambioContrasena entrar = new CambioContrasena();
     entrar.setVisible(true);
    }//GEN-LAST:event_jButtonOlvidoContraseñaActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void Mostar_ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostar_ContraseñaActionPerformed
       if(Mostar_Contraseña.isSelected()){
           Password_Usuario.setEchoChar((char)0);
       }else{
           Password_Usuario.setEchoChar('*');
       }
    }//GEN-LAST:event_Mostar_ContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loggin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contraseña;
    private javax.swing.JCheckBox Mostar_Contraseña;
    private javax.swing.JPasswordField Password_Usuario;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonOlvidoContraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBordeImagen;
    private javax.swing.JTextField jTextFieldUsusario;
    // End of variables declaration//GEN-END:variables
}
