/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_fundacion.vistas;

/**
 *
 * @author USUARIO
 */
public class PerfilCoordinador extends javax.swing.JFrame {

    /**
     * Creates new form PerfilCoordinador2
     */
    public PerfilCoordinador() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setTitle("PERFIL DEL COORDINADOR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btn_perfil = new javax.swing.JButton();
        BotInscrip = new javax.swing.JButton();
        btn_listados = new javax.swing.JButton();
        BotNotif = new javax.swing.JButton();
        NombresPC = new javax.swing.JLabel();
        CamNombre = new javax.swing.JTextField();
        ApelliPC = new javax.swing.JLabel();
        CamApellidos = new javax.swing.JTextField();
        Documento = new javax.swing.JLabel();
        CamDocPC = new javax.swing.JTextField();
        CodPC = new javax.swing.JLabel();
        CamCodPC = new javax.swing.JTextField();
        DirecPC = new javax.swing.JLabel();
        CampDirPC = new javax.swing.JTextField();
        TelePC = new javax.swing.JLabel();
        CamTelPC = new javax.swing.JTextField();
        RolPC = new javax.swing.JLabel();
        CamRolPC = new javax.swing.JTextField();
        FecNacPC = new javax.swing.JLabel();
        DateFecNacPC = new com.toedter.calendar.JDateChooser();
        CamImagPC = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PerfCoord = new javax.swing.JLabel();

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_perfil.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        btn_perfil.setText("Perfil");
        btn_perfil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_perfilMouseClicked(evt);
            }
        });
        jPanel1.add(btn_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 140, 30));

        BotInscrip.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        BotInscrip.setText("Inscripciones");
        BotInscrip.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotInscrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotInscripActionPerformed(evt);
            }
        });
        jPanel1.add(BotInscrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 140, 30));

        btn_listados.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        btn_listados.setText("Listados");
        btn_listados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_listados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_listadosMouseClicked(evt);
            }
        });
        jPanel1.add(btn_listados, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 140, 30));

        BotNotif.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        BotNotif.setText("Notificaciones");
        BotNotif.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotNotif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotNotifMouseClicked(evt);
            }
        });
        BotNotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotNotifActionPerformed(evt);
            }
        });
        jPanel1.add(BotNotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 140, 30));

        NombresPC.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        NombresPC.setText("Nombres:");
        jPanel1.add(NombresPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 80, 20));

        CamNombre.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(CamNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 370, -1));

        ApelliPC.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        ApelliPC.setText("Apellidos:");
        jPanel1.add(ApelliPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 90, 20));

        CamApellidos.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(CamApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 370, -1));

        Documento.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        Documento.setText("Documento:");
        jPanel1.add(Documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 100, 20));

        CamDocPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamDocPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(CamDocPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 370, -1));

        CodPC.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        CodPC.setText("Codigo:");
        jPanel1.add(CodPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 90, 20));

        CamCodPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamCodPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(CamCodPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 370, -1));

        DirecPC.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        DirecPC.setText("Direccion:");
        jPanel1.add(DirecPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 90, 20));

        CampDirPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CampDirPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(CampDirPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 370, -1));

        TelePC.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        TelePC.setText("Telefono:");
        jPanel1.add(TelePC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 80, 25));

        CamTelPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamTelPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(CamTelPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 370, -1));

        RolPC.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        RolPC.setText("Rol:");
        jPanel1.add(RolPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 70, 20));

        CamRolPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamRolPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(CamRolPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 370, -1));

        FecNacPC.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        FecNacPC.setText("Fecha de nacimiento:");
        jPanel1.add(FecNacPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, 160, -1));
        jPanel1.add(DateFecNacPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, 170, 30));

        CamImagPC.setBackground(new java.awt.Color(255, 255, 255));
        CamImagPC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout CamImagPCLayout = new javax.swing.GroupLayout(CamImagPC);
        CamImagPC.setLayout(CamImagPCLayout);
        CamImagPCLayout.setHorizontalGroup(
            CamImagPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        CamImagPCLayout.setVerticalGroup(
            CamImagPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        jPanel1.add(CamImagPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 220, 290));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoFNH2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PerfCoord.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        PerfCoord.setText("PERFIL COORDINADOR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 467, Short.MAX_VALUE)
                .addComponent(PerfCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(PerfCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 130));

        jScrollPane1.setViewportView(jPanel1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_perfilMouseClicked

    }//GEN-LAST:event_btn_perfilMouseClicked

    private void BotInscripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotInscripActionPerformed
        this.dispose();
        RegistroPersonas abrir = new RegistroPersonas();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotInscripActionPerformed

    private void btn_listadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_listadosMouseClicked
        this.dispose();
        Listado_Estudiantes abrir = new Listado_Estudiantes();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_listadosMouseClicked

    private void BotNotifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotNotifMouseClicked
        this.dispose();
        Notificaciones abrir = new Notificaciones();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotNotifMouseClicked

    private void BotNotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotNotifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotNotifActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApelliPC;
    private javax.swing.JButton BotInscrip;
    private javax.swing.JButton BotNotif;
    private javax.swing.JTextField CamApellidos;
    private javax.swing.JTextField CamCodPC;
    private javax.swing.JTextField CamDocPC;
    private javax.swing.JPanel CamImagPC;
    private javax.swing.JTextField CamNombre;
    private javax.swing.JTextField CamRolPC;
    private javax.swing.JTextField CamTelPC;
    private javax.swing.JTextField CampDirPC;
    private javax.swing.JLabel CodPC;
    private com.toedter.calendar.JDateChooser DateFecNacPC;
    private javax.swing.JLabel DirecPC;
    private javax.swing.JLabel Documento;
    private javax.swing.JLabel FecNacPC;
    private javax.swing.JLabel NombresPC;
    private javax.swing.JLabel PerfCoord;
    private javax.swing.JLabel RolPC;
    private javax.swing.JLabel TelePC;
    private javax.swing.JButton btn_listados;
    private javax.swing.JButton btn_perfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
