/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_fundacion.vistas;

/**
 *
 * @author USUARIO
 */
public class perfil_profesor extends javax.swing.JFrame {

    /**
     * Creates new form perfil_profesor
     */
    public perfil_profesor() {
        initComponents();
        this.setLocationRelativeTo(null);
        setVisible(true);
        setLocationRelativeTo(null);
        setTitle("PERFIL DEL PROFESOR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        logo_ = new javax.swing.JLabel();
        Nombres = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Apellidos = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        NDocumento = new javax.swing.JLabel();
        documento = new javax.swing.JTextField();
        CodigoE = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        DirPerPro = new javax.swing.JLabel();
        TelPerPro = new javax.swing.JLabel();
        RolPerPro = new javax.swing.JLabel();
        FecNAcPerPro = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        rol = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        btn_perfil = new javax.swing.JButton();
        btn_listados = new javax.swing.JButton();
        btn_notificaciones = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        logo_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_.setText("PERFIL DEL PROFESOR");
        jPanel1.add(logo_, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 210, 30));

        Nombres.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Nombres.setText("Nombres:");
        jPanel1.add(Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 80, 24));
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 380, -1));

        Apellidos.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Apellidos.setText("Apellidos:");
        jPanel1.add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 80, 24));
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 380, -1));

        NDocumento.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NDocumento.setText("Documento:");
        jPanel1.add(NDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 100, 20));
        jPanel1.add(documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 380, -1));

        CodigoE.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CodigoE.setText("Codigo:");
        jPanel1.add(CodigoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 70, 24));
        jPanel1.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 380, -1));

        DirPerPro.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        DirPerPro.setText("Direccion:");
        jPanel1.add(DirPerPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 90, 24));

        TelPerPro.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TelPerPro.setText("Telefono");
        jPanel1.add(TelPerPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 80, 24));

        RolPerPro.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        RolPerPro.setText("Rol:");
        jPanel1.add(RolPerPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 60, 24));

        FecNAcPerPro.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        FecNAcPerPro.setText("Fecha de nacimiento:");
        jPanel1.add(FecNAcPerPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 170, 24));
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 380, -1));
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 380, -1));
        jPanel1.add(rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 380, -1));

        btn_guardar.setBackground(new java.awt.Color(0, 204, 204));
        btn_guardar.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 160, 40));

        btn_editar.setBackground(new java.awt.Color(0, 204, 204));
        btn_editar.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 150, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 160, 200));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 130, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btn_perfil.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btn_perfil.setText("Perfil");
        btn_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_perfilMouseClicked(evt);
            }
        });

        btn_listados.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btn_listados.setText("Listados");
        btn_listados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_listadosMouseClicked(evt);
            }
        });

        btn_notificaciones.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btn_notificaciones.setText("Notificaciones");
        btn_notificaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_notificacionesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btn_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btn_listados, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(btn_notificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_listados, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_notificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 840, 60));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoFNH2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 120));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 710, 60));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jButton1.setText("SIGUIENTE");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, 120, 30));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jButton2.setText("ATRAS");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 590, 150, 30));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_perfilMouseClicked
        this.dispose();
        Perfil_estudiante abrir = new Perfil_estudiante();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_perfilMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
        Principal abrir = new Principal();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Perfil_estudiante abrir = new Perfil_estudiante();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        PerfilAdministrador abrir = new PerfilAdministrador();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_listadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_listadosMouseClicked
        this.dispose();
        Listado_Estudiantes abrir = new Listado_Estudiantes();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_listadosMouseClicked

    private void btn_notificacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_notificacionesMouseClicked
        this.dispose();
        Notificaciones abrir = new Notificaciones();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_notificacionesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellidos;
    private javax.swing.JLabel CodigoE;
    private javax.swing.JLabel DirPerPro;
    private javax.swing.JLabel FecNAcPerPro;
    private javax.swing.JLabel NDocumento;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel Nombres;
    private javax.swing.JLabel RolPerPro;
    private javax.swing.JLabel TelPerPro;
    private javax.swing.JTextField apellido;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_listados;
    private javax.swing.JButton btn_notificaciones;
    private javax.swing.JButton btn_perfil;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField documento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo_;
    private javax.swing.JTextField rol;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
