/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_fundacion.vistas;

/**
 *
 * @author USUARIO
 */
public class PerfilCoordinador extends javax.swing.JFrame {

    /**
     * Creates new form PerfilCoordinador2
     */
    public PerfilCoordinador() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setTitle("PERFIL DEL COORDINADOR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        PerfCoord = new javax.swing.JLabel();
        btn_perfil = new javax.swing.JButton();
        BotInscrip = new javax.swing.JButton();
        btn_listados = new javax.swing.JButton();
        BotNotif = new javax.swing.JButton();
        NombresPC = new javax.swing.JLabel();
        CamNombre = new javax.swing.JTextField();
        ApelliPC = new javax.swing.JLabel();
        CamApellidos = new javax.swing.JTextField();
        Documento = new javax.swing.JLabel();
        CamDocPC = new javax.swing.JTextField();
        CodPC = new javax.swing.JLabel();
        CamCodPC = new javax.swing.JTextField();
        DirecPC = new javax.swing.JLabel();
        CampDirPC = new javax.swing.JTextField();
        TelePC = new javax.swing.JLabel();
        CamTelPC = new javax.swing.JTextField();
        RolPC = new javax.swing.JLabel();
        CamRolPC = new javax.swing.JTextField();
        FecNacPC = new javax.swing.JLabel();
        DateFecNacPC = new com.toedter.calendar.JDateChooser();
        CamImagPC = new javax.swing.JPanel();
        BotSigPerCoor = new javax.swing.JButton();
        BotAtrPerCoor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PerfCoord.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        PerfCoord.setText("PERFIL COORDINADOR");
        jPanel1.add(PerfCoord, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 220, 27));

        btn_perfil.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btn_perfil.setText("Perfil");
        btn_perfil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_perfilMouseClicked(evt);
            }
        });
        jPanel1.add(btn_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        BotInscrip.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BotInscrip.setText("Inscripciones");
        BotInscrip.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotInscrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotInscripActionPerformed(evt);
            }
        });
        jPanel1.add(BotInscrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        btn_listados.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btn_listados.setText("Listados");
        btn_listados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_listados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_listadosMouseClicked(evt);
            }
        });
        jPanel1.add(btn_listados, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        BotNotif.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BotNotif.setText("Notificaciones");
        BotNotif.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotNotif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotNotifMouseClicked(evt);
            }
        });
        jPanel1.add(BotNotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        NombresPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NombresPC.setText("Nombres:");
        jPanel1.add(NombresPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 140, 20));

        CamNombre.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(CamNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 390, -1));

        ApelliPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ApelliPC.setText("Apellidos:");
        jPanel1.add(ApelliPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 140, 20));

        CamApellidos.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(CamApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 390, -1));

        Documento.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Documento.setText("Documento:");
        jPanel1.add(Documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 140, 20));

        CamDocPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamDocPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(CamDocPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 390, -1));

        CodPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CodPC.setText("Codigo:");
        jPanel1.add(CodPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 140, 20));

        CamCodPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamCodPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(CamCodPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 390, -1));

        DirecPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        DirecPC.setText("Direccion:");
        jPanel1.add(DirecPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 140, 30));

        CampDirPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CampDirPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(CampDirPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 390, -1));

        TelePC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TelePC.setText("Telefono:");
        jPanel1.add(TelePC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 140, 25));

        CamTelPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamTelPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(CamTelPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 390, -1));

        RolPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        RolPC.setText("Rol:");
        jPanel1.add(RolPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 140, 20));

        CamRolPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamRolPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(CamRolPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 390, -1));

        FecNacPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        FecNacPC.setText("Fecha de nacimiento:");
        jPanel1.add(FecNacPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 620, 160, -1));
        jPanel1.add(DateFecNacPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, 170, 30));

        CamImagPC.setBackground(new java.awt.Color(255, 255, 255));
        CamImagPC.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout CamImagPCLayout = new javax.swing.GroupLayout(CamImagPC);
        CamImagPC.setLayout(CamImagPCLayout);
        CamImagPCLayout.setHorizontalGroup(
            CamImagPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );
        CamImagPCLayout.setVerticalGroup(
            CamImagPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        jPanel1.add(CamImagPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 160, 210));

        BotSigPerCoor.setBackground(new java.awt.Color(204, 204, 204));
        BotSigPerCoor.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BotSigPerCoor.setText("SIGUIENTE");
        BotSigPerCoor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotSigPerCoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotSigPerCoorActionPerformed(evt);
            }
        });
        jPanel1.add(BotSigPerCoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 600, 160, 50));

        BotAtrPerCoor.setBackground(new java.awt.Color(204, 204, 204));
        BotAtrPerCoor.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BotAtrPerCoor.setText("ATRAS");
        BotAtrPerCoor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotAtrPerCoor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotAtrPerCoorMouseClicked(evt);
            }
        });
        jPanel1.add(BotAtrPerCoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, 170, 50));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoFNH2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 130));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 600, 70));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_perfilMouseClicked

    }//GEN-LAST:event_btn_perfilMouseClicked

    private void BotInscripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotInscripActionPerformed
        this.dispose();
        inscripciones abrir = new inscripciones();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotInscripActionPerformed

    private void btn_listadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_listadosMouseClicked
        this.dispose();
        Listado_Estudiantes abrir = new Listado_Estudiantes();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_listadosMouseClicked

    private void BotNotifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotNotifMouseClicked
        this.dispose();
        Notificaciones abrir = new Notificaciones();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotNotifMouseClicked

    private void BotSigPerCoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotSigPerCoorActionPerformed
        this.dispose();
        perfil_profesor abrir = new perfil_profesor();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotSigPerCoorActionPerformed

    private void BotAtrPerCoorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotAtrPerCoorMouseClicked
        this.dispose();
        PerfilAdministrador abrir = new PerfilAdministrador();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotAtrPerCoorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilCoordinador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApelliPC;
    private javax.swing.JButton BotAtrPerCoor;
    private javax.swing.JButton BotInscrip;
    private javax.swing.JButton BotNotif;
    private javax.swing.JButton BotSigPerCoor;
    private javax.swing.JTextField CamApellidos;
    private javax.swing.JTextField CamCodPC;
    private javax.swing.JTextField CamDocPC;
    private javax.swing.JPanel CamImagPC;
    private javax.swing.JTextField CamNombre;
    private javax.swing.JTextField CamRolPC;
    private javax.swing.JTextField CamTelPC;
    private javax.swing.JTextField CampDirPC;
    private javax.swing.JLabel CodPC;
    private com.toedter.calendar.JDateChooser DateFecNacPC;
    private javax.swing.JLabel DirecPC;
    private javax.swing.JLabel Documento;
    private javax.swing.JLabel FecNacPC;
    private javax.swing.JLabel NombresPC;
    private javax.swing.JLabel PerfCoord;
    private javax.swing.JLabel RolPC;
    private javax.swing.JLabel TelePC;
    private javax.swing.JButton btn_listados;
    private javax.swing.JButton btn_perfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
