/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_fundacion.vistas;

import Proyecto_fundacion.models.Personas;
//import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import java.util.Date;
import Proyecto_fundacion.controller.PersonasController;
import com.mycompany.proyecto_fundacion.Main;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class RegistroPersonas extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    private static int getSelectedRow() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    //Instanciar para poder utilizar
    Personas persona = new Personas();

    //Asi accedo a los metodos del registro
    PersonasController registro = new PersonasController();
    private String date;

    /**
     * Creates new form CreacionPersonas
     */
    public RegistroPersonas() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_btn_sisben = new javax.swing.ButtonGroup();
        Panel_principal = new javax.swing.JPanel();
        txt_tipo_documento = new javax.swing.JLabel();
        txt_numero_documento = new javax.swing.JLabel();
        txt_lugar_expedicion = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JLabel();
        txt_foto = new javax.swing.JLabel();
        txt_estrato = new javax.swing.JLabel();
        txt_fecha_nacimiento = new javax.swing.JLabel();
        txt_eps = new javax.swing.JLabel();
        txt_sisben = new javax.swing.JLabel();
        txt_categoria_sisben = new javax.swing.JLabel();
        txt_domicilio = new javax.swing.JLabel();
        txt_barrio = new javax.swing.JLabel();
        txt_localidad = new javax.swing.JLabel();
        txt_edad = new javax.swing.JLabel();
        box_tipo_documento = new javax.swing.JComboBox<>();
        Campo_num_documento = new javax.swing.JTextField();
        Campo_foto = new javax.swing.JTextField();
        Campo_lugar_expe1 = new javax.swing.JTextField();
        Campo_edad = new javax.swing.JTextField();
        Campo_nombres1 = new javax.swing.JTextField();
        Date_fecha_naci = new com.toedter.calendar.JDateChooser();
        Campo_apellidos1 = new javax.swing.JTextField();
        Campo_barrio = new javax.swing.JTextField();
        Campo_localidad = new javax.swing.JTextField();
        Campo_domicilio = new javax.swing.JTextField();
        Campo_eps = new javax.swing.JTextField();
        Radio_sisben_no = new javax.swing.JRadioButton();
        Radio_sisben_si = new javax.swing.JRadioButton();
        Campo_estrato1 = new javax.swing.JTextField();
        Campo_categoria_sis1 = new javax.swing.JTextField();
        txt_titulo = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        txt_ciudad_nacimiento = new javax.swing.JLabel();
        Campo_ciudad_nacimiento = new javax.swing.JTextField();
        jButton1Modificardatos = new javax.swing.JButton();
        Regresar_perfil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("fondo");
        setName("JFondo"); // NOI18N

        Panel_principal.setBackground(new java.awt.Color(255, 255, 255));
        Panel_principal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_tipo_documento.setText("Tipo de Documento:");

        txt_numero_documento.setText("Número de Documento:");

        txt_lugar_expedicion.setText("Lugar de Expedición:");

        txt_apellidos.setText("Apellidos:");

        txt_nombres.setText("Nombres:");

        txt_foto.setText("Fotografía:");

        txt_estrato.setText("Estrato:");

        txt_fecha_nacimiento.setText("Fecha de Nacimiento:");

        txt_eps.setText("Eps:");

        txt_sisben.setText("Sisben:");

        txt_categoria_sisben.setText("Categoria Sisben:");

        txt_domicilio.setText("Domicilio:");

        txt_barrio.setText("Barrio:");

        txt_localidad.setText("Localidad:");

        txt_edad.setText("Edad:");

        box_tipo_documento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Registro Civil", "Tarjeta de Identidad", "Cedula de Ciudadania", "Cedula de extranjeria", " " }));
        box_tipo_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_tipo_documentoActionPerformed(evt);
            }
        });

        Date_fecha_naci.setDateFormatString("dd/MM/yyyy");

        grupo_btn_sisben.add(Radio_sisben_no);
        Radio_sisben_no.setText("No");

        grupo_btn_sisben.add(Radio_sisben_si);
        Radio_sisben_si.setSelected(true);
        Radio_sisben_si.setText("Si");

        Campo_estrato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_estrato1ActionPerformed(evt);
            }
        });

        txt_titulo.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        txt_titulo.setForeground(new java.awt.Color(204, 51, 255));
        txt_titulo.setText("FORMULARIO ESTUDIANTES");

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        txt_ciudad_nacimiento.setText("Ciudad de Nacimiento:");

        jButton1Modificardatos.setText("ACTUALIZAR");
        jButton1Modificardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ModificardatosActionPerformed(evt);
            }
        });

        Regresar_perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa.png"))); // NOI18N
        Regresar_perfil.setText("Ir a Perfil");
        Regresar_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Regresar_perfilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_principalLayout = new javax.swing.GroupLayout(Panel_principal);
        Panel_principal.setLayout(Panel_principalLayout);
        Panel_principalLayout.setHorizontalGroup(
            Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_principalLayout.createSequentialGroup()
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(txt_titulo))
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Date_fecha_naci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_nombres)
                                .addComponent(box_tipo_documento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_tipo_documento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_lugar_expedicion)
                                .addComponent(txt_fecha_nacimiento)
                                .addComponent(Campo_lugar_expe1)
                                .addComponent(Campo_nombres1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_ciudad_nacimiento)
                            .addComponent(Campo_ciudad_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Campo_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_barrio)
                            .addComponent(txt_estrato)
                            .addComponent(Campo_estrato1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_categoria_sisben)
                            .addComponent(Campo_categoria_sis1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Campo_eps, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_eps)
                            .addGroup(Panel_principalLayout.createSequentialGroup()
                                .addComponent(Radio_sisben_si, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(Radio_sisben_no, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_sisben)
                            .addComponent(txt_domicilio)
                            .addComponent(Campo_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Campo_localidad, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Campo_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_numero_documento)
                            .addComponent(txt_foto)
                            .addComponent(Campo_num_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Campo_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_edad)
                            .addComponent(txt_apellidos)
                            .addComponent(Campo_apellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_localidad))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel_principalLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1Modificardatos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Regresar_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        Panel_principalLayout.setVerticalGroup(
            Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_principalLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(txt_titulo)
                .addGap(45, 45, 45)
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addComponent(txt_tipo_documento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box_tipo_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_lugar_expedicion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_lugar_expe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_nombres1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_fecha_nacimiento))
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_numero_documento)
                            .addGroup(Panel_principalLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(Campo_num_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addComponent(txt_foto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_apellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_apellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_edad)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Date_fecha_naci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Campo_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addComponent(txt_ciudad_nacimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_ciudad_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addComponent(txt_localidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addComponent(txt_barrio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addComponent(txt_domicilio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_principalLayout.createSequentialGroup()
                            .addComponent(txt_estrato)
                            .addGap(29, 29, 29))
                        .addComponent(Campo_estrato1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addComponent(txt_sisben)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Radio_sisben_si)
                            .addComponent(Radio_sisben_no))))
                .addGap(18, 18, 18)
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addComponent(txt_categoria_sisben)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Campo_categoria_sis1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_principalLayout.createSequentialGroup()
                        .addComponent(txt_eps)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_eps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(Panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Modificardatos)
                    .addComponent(btn_guardar)
                    .addComponent(Regresar_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

        //Metodo para cambiar el formato de fecha
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMMM-yyyy");
        String date = sdf.format(Date_fecha_naci.getDate());

        // Para setear (llenar) la informacion en el modelo Personas
        persona.setPerTipodeDocumento((String) box_tipo_documento.getSelectedItem());
        persona.setPerNumerodeDocumento(Campo_num_documento.getText());
        persona.setPerLugardeExpedicion(Campo_lugar_expe1.getText());
        persona.setPerNombres(Campo_nombres1.getText());
        persona.setPerApellidos(Campo_apellidos1.getText());
        persona.setPerFotografia(Campo_foto.getText());
        persona.setPerFechadeNacimiento(date);
        persona.setPerEdad(Campo_edad.getText());
        persona.setPerCiudadNacimiento(Campo_ciudad_nacimiento.getText());
        persona.setPerDomicilio(Campo_domicilio.getText());
        persona.setPerBarrio(Campo_barrio.getText());
        persona.setPerLocalidad(Campo_localidad.getText());
        persona.setPerEstrato(Campo_estrato1.getText());
        persona.setPerEps(Campo_eps.getText());
        if (Radio_sisben_si.isSelected()) {
            persona.setPerSisben(true);
        };
        if (Radio_sisben_no.isSelected()) {
            persona.setPerSisben(false);
        }
        persona.setPerSisbenCategoria(Campo_categoria_sis1.getText());

        boolean respuesta = registro.registrar(persona);

        //Si se guardo con exito, entonces
        if (respuesta) {

            //QUe le muestre al usuario una ventana
            JOptionPane.showMessageDialog(rootPane, "Se guardó el estudiante con éxito", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

            //Y aqui que limpie
            box_tipo_documento.setSelectedIndex(0);
            Campo_num_documento.setText("");
            Campo_lugar_expe1.setText("");
            Campo_nombres1.setText("");
            Campo_apellidos1.setText("");
            Campo_foto.setText("");
            Date_fecha_naci.setDateFormatString("01-01-2000"); //revisar
            Campo_edad.setText("");
            Campo_ciudad_nacimiento.setText("");
            Campo_domicilio.setText("");
            Campo_barrio.setText("");
            Campo_localidad.setText("");
            Campo_estrato1.setText("");
            Campo_eps.setText("");
            Campo_categoria_sis1.setText("");

        }

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void Campo_estrato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_estrato1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_estrato1ActionPerformed

    private void box_tipo_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_tipo_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_tipo_documentoActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButton1ModificardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ModificardatosActionPerformed

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMMM-yyyy");
        String date = sdf.format(Date_fecha_naci.getDate());
        persona.setPerTipodeDocumento((String) box_tipo_documento.getSelectedItem());
        persona.setPerNumerodeDocumento(Campo_num_documento.getText());
        persona.setPerLugardeExpedicion(Campo_lugar_expe1.getText());
        persona.setPerNombres(Campo_nombres1.getText());
        persona.setPerApellidos(Campo_apellidos1.getText());
        persona.setPerFotografia(Campo_foto.getText());
        persona.setPerFechadeNacimiento(date);
        persona.setPerEdad(Campo_edad.getText());
        persona.setPerCiudadNacimiento(Campo_ciudad_nacimiento.getText());
        persona.setPerDomicilio(Campo_domicilio.getText());
        persona.setPerBarrio(Campo_barrio.getText());
        persona.setPerLocalidad(Campo_localidad.getText());        
        persona.setPerEstrato(Campo_estrato1.getText());       
        persona.setPerEps(Campo_eps.getText());
        if(Radio_sisben_si.isSelected()) {
                persona.setPerSisben(true);
        };
        if(Radio_sisben_no.isSelected()) {
            persona.setPerSisben(false);
        }
        persona.setPerSisbenCategoria(Campo_categoria_sis1.getText());
        
        
        
        boolean respuesta = false;
        respuesta = registro.modificar(persona);
        
        if(respuesta) {
            
           //QUe le muestre al usuario una ventana
           JOptionPane.showMessageDialog(rootPane, "Se modificó con éxito", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
           
           //Y aqui que limpie
           box_tipo_documento.setSelectedIndex(0);
           Campo_num_documento.setText("");
           Campo_lugar_expe1.setText("");
           Campo_nombres1.setText("");
           Campo_apellidos1.setText("");
           Campo_foto.setText("");
           Date_fecha_naci.setDateFormatString("01-01-2000"); //revisar
           Campo_edad.setText(""); 
           Campo_ciudad_nacimiento.setText("");
           Campo_domicilio.setText("");
           Campo_barrio.setText("");
           Campo_localidad.setText("");
           Campo_estrato1.setText("");
           Campo_eps.setText("");
           Campo_categoria_sis1.setText("");
   
        }
    }//GEN-LAST:event_jButton1ModificardatosActionPerformed

    private void Regresar_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_perfilMouseClicked
        
        this.dispose();
        PerfilAdministrador entrar = new PerfilAdministrador();
        entrar.setVisible(true);
        
    }//GEN-LAST:event_Regresar_perfilMouseClicked
 

    public JButton getjButton1Modificardatos() {
        return jButton1Modificardatos;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Campo_apellidos1;
    private javax.swing.JTextField Campo_barrio;
    private javax.swing.JTextField Campo_categoria_sis1;
    private javax.swing.JTextField Campo_ciudad_nacimiento;
    private javax.swing.JTextField Campo_domicilio;
    private javax.swing.JTextField Campo_edad;
    private javax.swing.JTextField Campo_eps;
    private javax.swing.JTextField Campo_estrato1;
    private javax.swing.JTextField Campo_foto;
    private javax.swing.JTextField Campo_localidad;
    private javax.swing.JTextField Campo_lugar_expe1;
    private javax.swing.JTextField Campo_nombres1;
    private javax.swing.JTextField Campo_num_documento;
    private com.toedter.calendar.JDateChooser Date_fecha_naci;
    private javax.swing.JPanel Panel_principal;
    private javax.swing.JRadioButton Radio_sisben_no;
    private javax.swing.JRadioButton Radio_sisben_si;
    private javax.swing.JLabel Regresar_perfil;
    private javax.swing.JComboBox<String> box_tipo_documento;
    private javax.swing.JButton btn_guardar;
    private javax.swing.ButtonGroup grupo_btn_sisben;
    private javax.swing.JButton jButton1Modificardatos;
    private javax.swing.JLabel txt_apellidos;
    private javax.swing.JLabel txt_barrio;
    private javax.swing.JLabel txt_categoria_sisben;
    private javax.swing.JLabel txt_ciudad_nacimiento;
    private javax.swing.JLabel txt_domicilio;
    private javax.swing.JLabel txt_edad;
    private javax.swing.JLabel txt_eps;
    private javax.swing.JLabel txt_estrato;
    private javax.swing.JLabel txt_fecha_nacimiento;
    private javax.swing.JLabel txt_foto;
    private javax.swing.JLabel txt_localidad;
    private javax.swing.JLabel txt_lugar_expedicion;
    private javax.swing.JLabel txt_nombres;
    private javax.swing.JLabel txt_numero_documento;
    private javax.swing.JLabel txt_sisben;
    private javax.swing.JLabel txt_tipo_documento;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables
}
