/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_fundacion.vistas;

/**
 *
 * @author USUARIO
 */
public class Notificaciones extends javax.swing.JFrame {

    /**
     * Creates new form Notificaciones2
     */
    public Notificaciones() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setTitle("NOTIFICACIONES");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Notificaciones = new javax.swing.JLabel();
        GenerarAlerta = new javax.swing.JTextField();
        PanelAsistencia = new javax.swing.JPanel();
        AlerAsis1 = new javax.swing.JLabel();
        NomEstud = new javax.swing.JLabel();
        EstudianteAler = new javax.swing.JTextField();
        Hace5min = new javax.swing.JTextField();
        InasisA = new javax.swing.JLabel();
        InasistenciaClaseDe = new javax.swing.JTextField();
        PanelPsico1 = new javax.swing.JPanel();
        Hace5minAlerInas2 = new javax.swing.JTextField();
        EstudianteAsistencia2 = new javax.swing.JTextField();
        AlerInasistencia2 = new javax.swing.JTextField();
        NomEstudi = new javax.swing.JLabel();
        InasistenA = new javax.swing.JLabel();
        PanelPsico = new javax.swing.JPanel();
        Hace5minPsico = new javax.swing.JTextField();
        EstudianteAlerPsico = new javax.swing.JTextField();
        NomEst = new javax.swing.JLabel();
        InasistenciaPsico = new javax.swing.JTextField();
        AlerPsico = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        GenerPor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Alerta = new javax.swing.JLabel();
        TipoDeAlerta = new javax.swing.JLabel();
        AsistenciaAlert = new javax.swing.JComboBox<>();
        GeneradaPor = new javax.swing.JLabel();
        AsistenciaAler1 = new javax.swing.JComboBox<>();
        AlertEstudian3 = new javax.swing.JLabel();
        EstudianteAlerta = new javax.swing.JComboBox<>();
        Observacion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        TipoDeAlerta1 = new javax.swing.JLabel();
        AsistenciaAlert3 = new javax.swing.JComboBox<>();
        AsistenciaAlert2 = new javax.swing.JComboBox<>();
        Alerta1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        GeneradaPor1 = new javax.swing.JLabel();
        AlertEstudian2 = new javax.swing.JLabel();
        EstudianteAlerta1 = new javax.swing.JComboBox<>();
        Observacion1 = new javax.swing.JLabel();
        PanelPsico2 = new javax.swing.JPanel();
        Hace5minPsico1 = new javax.swing.JTextField();
        EstudianteAlerPsico1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        InasistenciaPsico1 = new javax.swing.JTextField();
        AlePsicol = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        AlertEstudian1 = new javax.swing.JLabel();
        BotSiguiPerAdm1 = new javax.swing.JButton();
        BotSiguiPerEst = new javax.swing.JButton();
        SiguieNot = new javax.swing.JButton();
        AntNot = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Notificaciones.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Notificaciones.setText("Notificaciones");
        jPanel1.add(Notificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 120, 30));

        GenerarAlerta.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        GenerarAlerta.setText("GENERAR ALERTA");
        GenerarAlerta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GenerarAlerta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenerarAlertaMouseClicked(evt);
            }
        });
        GenerarAlerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarAlertaActionPerformed(evt);
            }
        });
        jPanel1.add(GenerarAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 200, 40));

        PanelAsistencia.setBorder(new javax.swing.border.MatteBorder(null));

        AlerAsis1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        AlerAsis1.setText("Alerta - Asistencia 1");

        NomEstud.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        NomEstud.setText("Estudiante ");

        EstudianteAler.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        EstudianteAler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudianteAlerActionPerformed(evt);
            }
        });

        Hace5min.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Hace5min.setText("Hace 5 min");

        InasisA.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        InasisA.setText("Inasistencia a clase de:");

        InasistenciaClaseDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InasistenciaClaseDeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAsistenciaLayout = new javax.swing.GroupLayout(PanelAsistencia);
        PanelAsistencia.setLayout(PanelAsistenciaLayout);
        PanelAsistenciaLayout.setHorizontalGroup(
            PanelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAsistenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAsistenciaLayout.createSequentialGroup()
                        .addComponent(AlerAsis1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hace5min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(NomEstud, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(InasisA, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EstudianteAler, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                        .addComponent(InasistenciaClaseDe)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAsistenciaLayout.setVerticalGroup(
            PanelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAsistenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlerAsis1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hace5min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(NomEstud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EstudianteAler, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InasisA)
                .addGap(12, 12, 12)
                .addComponent(InasistenciaClaseDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(PanelAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 290, 160));

        PanelPsico1.setBorder(new javax.swing.border.MatteBorder(null));

        Hace5minAlerInas2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Hace5minAlerInas2.setText("Hace 5 min");

        EstudianteAsistencia2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        EstudianteAsistencia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudianteAsistencia2ActionPerformed(evt);
            }
        });

        NomEstudi.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        NomEstudi.setText("Estudiante");

        InasistenA.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        InasistenA.setText("Inasistencia a clase de:");

        javax.swing.GroupLayout PanelPsico1Layout = new javax.swing.GroupLayout(PanelPsico1);
        PanelPsico1.setLayout(PanelPsico1Layout);
        PanelPsico1Layout.setHorizontalGroup(
            PanelPsico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPsico1Layout.createSequentialGroup()
                .addGroup(PanelPsico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPsico1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(NomEstudi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPsico1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelPsico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InasistenA, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelPsico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Hace5minAlerInas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanelPsico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EstudianteAsistencia2)
                                    .addComponent(AlerInasistencia2, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPsico1Layout.setVerticalGroup(
            PanelPsico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPsico1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hace5minAlerInas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomEstudi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EstudianteAsistencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InasistenA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlerInasistencia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(PanelPsico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 300, 160));

        PanelPsico.setBorder(new javax.swing.border.MatteBorder(null));
        PanelPsico.setLayout(null);

        Hace5minPsico.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Hace5minPsico.setText("Hace 5 min");
        PanelPsico.add(Hace5minPsico);
        Hace5minPsico.setBounds(180, 10, 70, 22);

        EstudianteAlerPsico.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        EstudianteAlerPsico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudianteAlerPsicoActionPerformed(evt);
            }
        });
        PanelPsico.add(EstudianteAlerPsico);
        EstudianteAlerPsico.setBounds(7, 57, 270, 22);

        NomEst.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        NomEst.setText("Estudiante ");
        PanelPsico.add(NomEst);
        NomEst.setBounds(7, 36, 185, 16);
        PanelPsico.add(InasistenciaPsico);
        InasistenciaPsico.setBounds(10, 110, 270, 20);

        AlerPsico.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        AlerPsico.setText("Alerta - Psicologìa");
        PanelPsico.add(AlerPsico);
        AlerPsico.setBounds(10, 10, 185, 19);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        PanelPsico.add(jScrollPane4);
        jScrollPane4.setBounds(10, 140, 270, 70);

        GenerPor.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        GenerPor.setText("Generada Por:");
        PanelPsico.add(GenerPor);
        GenerPor.setBounds(10, 90, 81, 16);

        jPanel1.add(PanelPsico, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 300, 230));

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(null);

        Alerta.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Alerta.setText("Alerta");
        jPanel2.add(Alerta);
        Alerta.setBounds(20, 10, 41, 19);

        TipoDeAlerta.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        TipoDeAlerta.setText("Tipo de Alerta:");
        jPanel2.add(TipoDeAlerta);
        TipoDeAlerta.setBounds(21, 45, 81, 16);

        AsistenciaAlert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asistencia" }));
        jPanel2.add(AsistenciaAlert);
        AsistenciaAlert.setBounds(125, 41, 160, 20);

        GeneradaPor.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        GeneradaPor.setText("Generada Por:");
        jPanel2.add(GeneradaPor);
        GeneradaPor.setBounds(20, 70, 81, 20);

        jPanel2.add(AsistenciaAler1);
        AsistenciaAler1.setBounds(125, 69, 160, 22);

        AlertEstudian3.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        AlertEstudian3.setText("Estudiante");
        jPanel2.add(AlertEstudian3);
        AlertEstudian3.setBounds(20, 100, 60, 16);

        jPanel2.add(EstudianteAlerta);
        EstudianteAlerta.setBounds(125, 97, 160, 22);

        Observacion.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Observacion.setText("Observaciones");
        jPanel2.add(Observacion);
        Observacion.setBounds(20, 140, 86, 16);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Inasistencia a la clase de danzas\n");
        jScrollPane2.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 160, 270, 150);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 310, 330));

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setLayout(null);

        TipoDeAlerta1.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        TipoDeAlerta1.setText("Tipo de Alerta:");
        jPanel3.add(TipoDeAlerta1);
        TipoDeAlerta1.setBounds(17, 43, 81, 16);

        AsistenciaAlert3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asistencia" }));
        jPanel3.add(AsistenciaAlert3);
        AsistenciaAlert3.setBounds(121, 39, 220, 20);

        jPanel3.add(AsistenciaAlert2);
        AsistenciaAlert2.setBounds(121, 67, 220, 22);

        Alerta1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Alerta1.setText("Alerta");
        jPanel3.add(Alerta1);
        Alerta1.setBounds(17, 7, 41, 19);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Ingrese un comentario adicional\n\n");
        jScrollPane3.setViewportView(jTextArea2);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(20, 160, 310, 150);

        GeneradaPor1.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        GeneradaPor1.setText("Generada Por:");
        jPanel3.add(GeneradaPor1);
        GeneradaPor1.setBounds(20, 70, 81, 16);

        AlertEstudian2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        AlertEstudian2.setText("Estudiante");
        jPanel3.add(AlertEstudian2);
        AlertEstudian2.setBounds(20, 100, 60, 16);

        jPanel3.add(EstudianteAlerta1);
        EstudianteAlerta1.setBounds(120, 100, 220, 22);

        Observacion1.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Observacion1.setText("Observaciones");
        jPanel3.add(Observacion1);
        Observacion1.setBounds(20, 140, 86, 16);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 360, 330));

        PanelPsico2.setBorder(new javax.swing.border.MatteBorder(null));
        PanelPsico2.setLayout(null);

        Hace5minPsico1.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Hace5minPsico1.setText("Hace 5 min");
        PanelPsico2.add(Hace5minPsico1);
        Hace5minPsico1.setBounds(193, 7, 70, 22);

        EstudianteAlerPsico1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        EstudianteAlerPsico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudianteAlerPsico1ActionPerformed(evt);
            }
        });
        PanelPsico2.add(EstudianteAlerPsico1);
        EstudianteAlerPsico1.setBounds(7, 57, 270, 22);

        jLabel10.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel10.setText("Estudiante ");
        PanelPsico2.add(jLabel10);
        jLabel10.setBounds(7, 36, 185, 16);
        PanelPsico2.add(InasistenciaPsico1);
        InasistenciaPsico1.setBounds(7, 109, 270, 20);

        AlePsicol.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        AlePsicol.setText("Alerta - Psicologìa");
        PanelPsico2.add(AlePsicol);
        AlePsicol.setBounds(10, 10, 185, 19);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        PanelPsico2.add(jScrollPane5);
        jScrollPane5.setBounds(10, 140, 270, 110);

        AlertEstudian1.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        AlertEstudian1.setText("Generada Por:");
        PanelPsico2.add(AlertEstudian1);
        AlertEstudian1.setBounds(10, 90, 81, 16);

        jPanel1.add(PanelPsico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, 300, 260));

        BotSiguiPerAdm1.setBackground(new java.awt.Color(204, 204, 204));
        BotSiguiPerAdm1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BotSiguiPerAdm1.setText("PERFIL COORDINADOR");
        BotSiguiPerAdm1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotSiguiPerAdm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotSiguiPerAdm1MouseClicked(evt);
            }
        });
        BotSiguiPerAdm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotSiguiPerAdm1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotSiguiPerAdm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 260, 30));

        BotSiguiPerEst.setBackground(new java.awt.Color(204, 204, 204));
        BotSiguiPerEst.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BotSiguiPerEst.setText("      PERFIL PROFESOR");
        BotSiguiPerEst.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotSiguiPerEst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotSiguiPerEstMouseClicked(evt);
            }
        });
        BotSiguiPerEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotSiguiPerEstActionPerformed(evt);
            }
        });
        jPanel1.add(BotSiguiPerEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 700, 270, 30));

        SiguieNot.setBackground(new java.awt.Color(204, 204, 204));
        SiguieNot.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        SiguieNot.setText("PSICOLOGIA");
        SiguieNot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SiguieNot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SiguieNotMouseClicked(evt);
            }
        });
        SiguieNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguieNotActionPerformed(evt);
            }
        });
        jPanel1.add(SiguieNot, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 700, 200, 30));

        AntNot.setBackground(new java.awt.Color(204, 204, 204));
        AntNot.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        AntNot.setText("ANTERIOR");
        AntNot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AntNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntNotActionPerformed(evt);
            }
        });
        jPanel1.add(AntNot, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 700, 150, 30));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoFNH2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 130));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 680, 60));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1112, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerarAlertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenerarAlertaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerarAlertaMouseClicked

    private void GenerarAlertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarAlertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerarAlertaActionPerformed

    private void EstudianteAlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudianteAlerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstudianteAlerActionPerformed

    private void InasistenciaClaseDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InasistenciaClaseDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InasistenciaClaseDeActionPerformed

    private void EstudianteAsistencia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudianteAsistencia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstudianteAsistencia2ActionPerformed

    private void EstudianteAlerPsicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudianteAlerPsicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstudianteAlerPsicoActionPerformed

    private void EstudianteAlerPsico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudianteAlerPsico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstudianteAlerPsico1ActionPerformed

    private void BotSiguiPerAdm1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotSiguiPerAdm1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BotSiguiPerAdm1MouseClicked

    private void BotSiguiPerAdm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotSiguiPerAdm1ActionPerformed
        this.dispose();
        PerfilCoordinador abrir = new PerfilCoordinador();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotSiguiPerAdm1ActionPerformed

    private void BotSiguiPerEstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotSiguiPerEstMouseClicked
        this.dispose();
        PerfilCoordinador abrir = new PerfilCoordinador();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotSiguiPerEstMouseClicked

    private void BotSiguiPerEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotSiguiPerEstActionPerformed
        this.dispose();
        perfil_profesor abrir = new perfil_profesor();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotSiguiPerEstActionPerformed

    private void SiguieNotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SiguieNotMouseClicked
        this.dispose();
        Perfil_estudiante inscrip = new Perfil_estudiante();
        inscrip.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SiguieNotMouseClicked

    private void SiguieNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguieNotActionPerformed
        this.dispose();
        psicologia abrir = new psicologia();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SiguieNotActionPerformed

    private void AntNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntNotActionPerformed
        this.dispose();
        PerfilAdministrador regr = new PerfilAdministrador();
        regr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AntNotActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlePsicol;
    private javax.swing.JLabel AlerAsis1;
    private javax.swing.JTextField AlerInasistencia2;
    private javax.swing.JLabel AlerPsico;
    private javax.swing.JLabel AlertEstudian1;
    private javax.swing.JLabel AlertEstudian2;
    private javax.swing.JLabel AlertEstudian3;
    private javax.swing.JLabel Alerta;
    private javax.swing.JLabel Alerta1;
    private javax.swing.JButton AntNot;
    private javax.swing.JComboBox<String> AsistenciaAler1;
    private javax.swing.JComboBox<String> AsistenciaAlert;
    private javax.swing.JComboBox<String> AsistenciaAlert2;
    private javax.swing.JComboBox<String> AsistenciaAlert3;
    private javax.swing.JButton BotSiguiPerAdm1;
    private javax.swing.JButton BotSiguiPerEst;
    private javax.swing.JTextField EstudianteAler;
    private javax.swing.JTextField EstudianteAlerPsico;
    private javax.swing.JTextField EstudianteAlerPsico1;
    private javax.swing.JComboBox<String> EstudianteAlerta;
    private javax.swing.JComboBox<String> EstudianteAlerta1;
    private javax.swing.JTextField EstudianteAsistencia2;
    private javax.swing.JLabel GenerPor;
    private javax.swing.JLabel GeneradaPor;
    private javax.swing.JLabel GeneradaPor1;
    private javax.swing.JTextField GenerarAlerta;
    private javax.swing.JTextField Hace5min;
    private javax.swing.JTextField Hace5minAlerInas2;
    private javax.swing.JTextField Hace5minPsico;
    private javax.swing.JTextField Hace5minPsico1;
    private javax.swing.JLabel InasisA;
    private javax.swing.JLabel InasistenA;
    private javax.swing.JTextField InasistenciaClaseDe;
    private javax.swing.JTextField InasistenciaPsico;
    private javax.swing.JTextField InasistenciaPsico1;
    private javax.swing.JLabel NomEst;
    private javax.swing.JLabel NomEstud;
    private javax.swing.JLabel NomEstudi;
    private javax.swing.JLabel Notificaciones;
    private javax.swing.JLabel Observacion;
    private javax.swing.JLabel Observacion1;
    private javax.swing.JPanel PanelAsistencia;
    private javax.swing.JPanel PanelPsico;
    private javax.swing.JPanel PanelPsico1;
    private javax.swing.JPanel PanelPsico2;
    private javax.swing.JButton SiguieNot;
    private javax.swing.JLabel TipoDeAlerta;
    private javax.swing.JLabel TipoDeAlerta1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables
}
