/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_fundacion.vistas;

//import java.text.SimpleDateFormat;

//import com.toedter.calendar.JDateChooser;
//import java.text.SimpleDateFormat;
import java.util.Date;
import Proyecto_fundacion.controller.PerfilAdministradorController;
import com.mycompany.proyecto_fundacion.Main;
//import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import javax.swing.JButton;
//import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class PerfilAdministrador extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    
    /**
     * Creates new form PerfilAdministrador2
     */
    public PerfilAdministrador() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setTitle("PERFIL DEL ADMINISTRADOR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        logo2 = new javax.swing.JLabel();
        Perfiles = new javax.swing.JComboBox<>();
        btn_RegistroPersonas = new javax.swing.JButton();
        btn_listados = new javax.swing.JButton();
        btn_notificaciones = new javax.swing.JButton();
        btn_configuracion = new javax.swing.JButton();
        NomAdmi = new javax.swing.JLabel();
        NomAdm = new javax.swing.JTextField();
        ApelAdm = new javax.swing.JLabel();
        apellidos = new javax.swing.JTextField();
        DocAdm = new javax.swing.JLabel();
        documentos = new javax.swing.JTextField();
        CodPerAdm = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        DirPerAdm = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        TelPerAdm = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        RolPerAdm = new javax.swing.JLabel();
        rol = new javax.swing.JTextField();
        FecPerAdm = new javax.swing.JLabel();
        jDateChooser1FecNacAdm = new com.toedter.calendar.JDateChooser();
        FotoEstudi = new javax.swing.JPanel();
        BotSiguiPerAdm1 = new javax.swing.JButton();
        BotSiguiPerEst = new javax.swing.JButton();
        BotSiguiPerAdm2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1100, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo2.setBackground(new java.awt.Color(153, 153, 153));
        logo2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        logo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo2.setText("PERFIL ADMINISTRADOR");
        jPanel1.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 230, 30));

        Perfiles.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Perfiles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coordinador", "Estudiante", "Profesor", "" }));
        Perfiles.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                PerfilesPopupMenuWillBecomeVisible(evt);
            }
        });
        Perfiles.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                PerfilesCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        Perfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilesActionPerformed(evt);
            }
        });
        jPanel1.add(Perfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 180, 30));

        btn_RegistroPersonas.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btn_RegistroPersonas.setText("Registro personas");
        btn_RegistroPersonas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_RegistroPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistroPersonasActionPerformed(evt);
            }
        });
        jPanel1.add(btn_RegistroPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 170, 30));

        btn_listados.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btn_listados.setText("Ir a Listados");
        btn_listados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_listados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_listadosMouseClicked(evt);
            }
        });
        btn_listados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listadosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_listados, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 130, 30));

        btn_notificaciones.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btn_notificaciones.setText("Notificaciones");
        btn_notificaciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_notificaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_notificacionesMouseClicked(evt);
            }
        });
        btn_notificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_notificacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_notificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 170, 30));

        btn_configuracion.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btn_configuracion.setText("Configuracion");
        btn_configuracion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configuracionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_configuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 170, 30));

        NomAdmi.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NomAdmi.setText("Nombres:");
        jPanel1.add(NomAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 100, 25));

        NomAdm.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NomAdm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        NomAdm.setCaretColor(new java.awt.Color(153, 153, 153));
        NomAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomAdmActionPerformed(evt);
            }
        });
        jPanel1.add(NomAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 380, 20));

        ApelAdm.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ApelAdm.setText("Apellidos:");
        jPanel1.add(ApelAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 100, 25));

        apellidos.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        apellidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        apellidos.setCaretColor(new java.awt.Color(153, 153, 153));
        jPanel1.add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 380, 20));

        DocAdm.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        DocAdm.setText("Documento:");
        jPanel1.add(DocAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 120, 40));

        documentos.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        documentos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        documentos.setCaretColor(new java.awt.Color(153, 153, 153));
        jPanel1.add(documentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 380, 20));

        CodPerAdm.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CodPerAdm.setText("Codigo:");
        jPanel1.add(CodPerAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 90, 40));

        codigo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        codigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        codigo.setCaretColor(new java.awt.Color(153, 153, 153));
        jPanel1.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 380, 20));

        DirPerAdm.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        DirPerAdm.setText("Direccion:");
        jPanel1.add(DirPerAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 80, 50));

        direccion.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        direccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        direccion.setCaretColor(new java.awt.Color(153, 153, 153));
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 380, 20));

        TelPerAdm.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TelPerAdm.setText("Telefono:");
        jPanel1.add(TelPerAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 80, 60));

        telefono.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        telefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        telefono.setCaretColor(new java.awt.Color(153, 153, 153));
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 380, 20));

        RolPerAdm.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        RolPerAdm.setText("Rol:");
        jPanel1.add(RolPerAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 70, 30));

        rol.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        rol.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        rol.setCaretColor(new java.awt.Color(153, 153, 153));
        jPanel1.add(rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 380, 20));

        FecPerAdm.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        FecPerAdm.setText("Fecha de nacimiento:");
        jPanel1.add(FecPerAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 160, 30));
        jPanel1.add(jDateChooser1FecNacAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 180, 30));

        FotoEstudi.setBackground(new java.awt.Color(255, 255, 255));
        FotoEstudi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        FotoEstudi.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout FotoEstudiLayout = new javax.swing.GroupLayout(FotoEstudi);
        FotoEstudi.setLayout(FotoEstudiLayout);
        FotoEstudiLayout.setHorizontalGroup(
            FotoEstudiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        FotoEstudiLayout.setVerticalGroup(
            FotoEstudiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        jPanel1.add(FotoEstudi, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 170, 220));

        BotSiguiPerAdm1.setBackground(new java.awt.Color(204, 204, 204));
        BotSiguiPerAdm1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BotSiguiPerAdm1.setText("PERFIL COORDINADOR");
        BotSiguiPerAdm1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotSiguiPerAdm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotSiguiPerAdm1MouseClicked(evt);
            }
        });
        BotSiguiPerAdm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotSiguiPerAdm1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotSiguiPerAdm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 260, 20));

        BotSiguiPerEst.setBackground(new java.awt.Color(204, 204, 204));
        BotSiguiPerEst.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BotSiguiPerEst.setText("      PERFIL PROFESOR");
        BotSiguiPerEst.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotSiguiPerEst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotSiguiPerEstMouseClicked(evt);
            }
        });
        BotSiguiPerEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotSiguiPerEstActionPerformed(evt);
            }
        });
        jPanel1.add(BotSiguiPerEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, 260, 20));

        BotSiguiPerAdm2.setBackground(new java.awt.Color(204, 204, 204));
        BotSiguiPerAdm2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BotSiguiPerAdm2.setText("   PERFIL ESTUDIANTE");
        BotSiguiPerAdm2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotSiguiPerAdm2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotSiguiPerAdm2MouseClicked(evt);
            }
        });
        BotSiguiPerAdm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotSiguiPerAdm2ActionPerformed(evt);
            }
        });
        jPanel1.add(BotSiguiPerAdm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 600, 260, 20));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoFNH2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 130));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 680, 60));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PerfilesPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_PerfilesPopupMenuWillBecomeVisible
      
    }//GEN-LAST:event_PerfilesPopupMenuWillBecomeVisible

    private void PerfilesCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_PerfilesCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilesCaretPositionChanged

    private void PerfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilesActionPerformed

    }//GEN-LAST:event_PerfilesActionPerformed

    private void btn_RegistroPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistroPersonasActionPerformed
        this.dispose();
        RegistroPersonas abrir = new RegistroPersonas();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_RegistroPersonasActionPerformed

    private void btn_listadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_listadosMouseClicked
       
    }//GEN-LAST:event_btn_listadosMouseClicked

    private void btn_listadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listadosActionPerformed
        this.dispose();
        Listado_Estudiantes abrir = new Listado_Estudiantes();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_listadosActionPerformed

    private void btn_notificacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_notificacionesMouseClicked
        this.dispose();
        Notificaciones abrir = new Notificaciones();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_notificacionesMouseClicked

    private void btn_notificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_notificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_notificacionesActionPerformed

    private void btn_configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configuracionActionPerformed
        this.dispose();
        configuraciones abrir = new configuraciones();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_configuracionActionPerformed

    private void NomAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomAdmActionPerformed

    private void BotSiguiPerAdm1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotSiguiPerAdm1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BotSiguiPerAdm1MouseClicked

    private void BotSiguiPerAdm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotSiguiPerAdm1ActionPerformed
        this.dispose();
        PerfilCoordinador abrir = new PerfilCoordinador();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotSiguiPerAdm1ActionPerformed

    private void BotSiguiPerEstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotSiguiPerEstMouseClicked
        this.dispose();
        PerfilCoordinador abrir = new PerfilCoordinador();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotSiguiPerEstMouseClicked

    private void BotSiguiPerEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotSiguiPerEstActionPerformed
        this.dispose();
        perfil_profesor abrir = new perfil_profesor();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotSiguiPerEstActionPerformed

    private void BotSiguiPerAdm2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotSiguiPerAdm2MouseClicked
        this.dispose();
        Perfil_estudiante abrir = new Perfil_estudiante();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotSiguiPerAdm2MouseClicked

    private void BotSiguiPerAdm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotSiguiPerAdm2ActionPerformed
        
    }//GEN-LAST:event_BotSiguiPerAdm2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApelAdm;
    private javax.swing.JButton BotSiguiPerAdm1;
    private javax.swing.JButton BotSiguiPerAdm2;
    private javax.swing.JButton BotSiguiPerEst;
    private javax.swing.JLabel CodPerAdm;
    private javax.swing.JLabel DirPerAdm;
    private javax.swing.JLabel DocAdm;
    private javax.swing.JLabel FecPerAdm;
    private javax.swing.JPanel FotoEstudi;
    private javax.swing.JTextField NomAdm;
    private javax.swing.JLabel NomAdmi;
    private javax.swing.JComboBox<String> Perfiles;
    private javax.swing.JLabel RolPerAdm;
    private javax.swing.JLabel TelPerAdm;
    private javax.swing.JTextField apellidos;
    private javax.swing.JButton btn_RegistroPersonas;
    private javax.swing.JButton btn_configuracion;
    private javax.swing.JButton btn_listados;
    private javax.swing.JButton btn_notificaciones;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField documentos;
    private com.toedter.calendar.JDateChooser jDateChooser1FecNacAdm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo2;
    private javax.swing.JTextField rol;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables

    private static class Date_fecha_naci {

        private static Object getDate() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public Date_fecha_naci() {
        }
    }
}
